### ISSUE TITLE
Release 1.7.2

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#1000]
Hi please release 1.7.2. Reason because currently some of the changes are said to be included in the 1.7.x release aren't such as the raw fix.

**Comment by RedShift1** [comment]
Can you say which issue exactly the "raw" fix is?

**Comment by paladox** [comment]
It fixes the issue when you had a repo that looked like this

Example/Example/Example

It would not show the raw files of the repo looked like that but is now fixed.

The repo had to look like Example for it to work but now works with all repos.

**Comment by bviktor** [comment]
You could always just build it on your own.
