### ISSUE TITLE
Pack size of GitRepo is much bigger than local clone

### ISSUE THREAD

**Issue by mliebelt** [gitblit/gitblit#1005]
We have faced the strange situation that a repository on the server was around 12 GB big, where a local clone was only around 60 MB big (see the [question on stackoverflow](http://stackoverflow.com/questions/34809571/git-repository-on-server-is-much-bigger-than-local-clone-with-all-branches) about it).

We cannot explain why this was the case, but we would like to know if the repository on the server is shrunk on a regular time basis. At least the UI tells us though:

* Go to `Repository > Edit`
* There the tab `GC`
* You will read the sentence: "The garbage collector will pack loose objects pushed from clients and will remove unreferenced objects from the repository."
* We have not changed the default there (7 days, ...)

However, after our operation team has done a `git gc --prune --agressive` on the repository, the repository shrunk from 12 GB to ~ 110 MB.

So these are 2 questions:
* Is it dangerous to do something by hand like that?
* Is that different to doing an automatic GC triggered by GitBlit?

**Comment by gitblit** [comment]
GC is still an experimental feature of Gitblit.  What version of Gitblit are you running?  Did you enable the GC feature?  It's disabled by default.

**Comment by mliebelt** [comment]
Thank's for the hint, so I misunderstood the UI. I just had a look, saw the tab "GC" and the default values, but after hoovering over the values, I saw I cannot change them. So I think the feature is disabled at the moment.

I have found the documentation about the settings for garbabe collection. It reads for me that this will lead to the call of `git gc --prune` without `--agressive`, is that true?

Btw, you can close the ticket then.

**Comment by gitblit** [comment]
Gitblit, being nearly pure Java, does not use native git.  Instead the JGit garbage collector is used.  While the JGit GC may (now) support prune and/or aggressive these options are not specified since initially JGit didn't support hardly any values here and Gitblit's GC service has not been touched in a while.
