### ISSUE TITLE
Spaces in URL

### ISSUE THREAD

**Issue by ManniManfred** [gitblit/gitblit#1006]
Hi, I have Problems cloning a Repository, that is in a folder with a space.
I tried 
a) git clone http://entwsrv01/r/Tests/Leerzeichen%20Test/Test1.git
b) git clone "http://entwsrv01/r/Tests/Leerzeichen Test/Test1.git"
both results in "fatal: repository ... not found"
What I'm doing wrong? Or isn't it supported?

**Comment by gitblit** [comment]
Whilespace is illegal in repo names.

http://gitblit.com/administration.html#H3
