### ISSUE TITLE
Submodules in Multiuser Environment

### ISSUE THREAD

**Issue by bernhardberger** [gitblit/gitblit#1015]
We've got the following annoying issue:

we have a multiuser environment and a bunch of projects/repositories using submodules:

user1@main-project1
   user2@submodule
   user3@submodule

If we have the listed constellation it is a PITA to check out such projects as git always wants the credentials for user2 and user3 when initializing submodules.. 

Gitlab has for example a central user for checkout (git@xy) and does check che access rights somehow internally.. is something like that possible with GitBlit?

**Comment by gitblit** [comment]
You are not required to specify the username as part of the URL unless this is the SSH transport.  If you are talking about SSH, there is open issue #904 to implement support for identifying the user solely by the provided public key.  No one is actively working on that issue at the moment.

**Comment by bernhardberger** [comment]
Yeah, I'm talking about ssh.. Anything else doesnt make sense as I don't
want to enter my credentials 20+ times per project.. :/
Am 05.02.2016 14:06 schrieb "James Moger" <notifications@github.com>:

**Comment by fzs** [comment]
Closing as duplicate of #904.
