### ISSUE TITLE
Service gets slow by very short time

### ISSUE THREAD

**Issue by tomposmiko** [gitblit/gitblit#1016]
version: 252dc07d7f85cc344b5919bb7c6166ef84b2102e

After a very short time (maybe 1-2 hours) the service gets incredibly slow, a simple pull/push takes about a minute.

**Comment by gitblit** [comment]
If you rebuild and deploy from the parent commit it does not behave this way?

**Comment by tomposmiko** [comment]
I haven't tried it yet.
I mean I upgraded from 2015-12-28. Stepping back fixed the issue, so there was something in January. Do you have a good tip?

**Comment by paulsputer** [comment]
Hi @tomposmiko can you provide some further details to assist in debugging this, perhaps adding `GIT_TRACE=1` before your git command could help us identify where the hold up is occurring.

The only change that I'm aware of in the past month that modifies the JGit servlet route is additions to flag and view filestore (Git-LFS) items.  I'm yet to update my linux box but running `252dc07` in debug on windows over several hours hasn't shown up anything.  

How large/often are the changesets and are you using the Git-LFS or other some hooks?

**Comment by tomposmiko** [comment]
Believe or not, I cannot reproduce it since than.
In middle of January I built a new version and I saw this issue. I changed back to the prior version, because didn't have time to work on this.
Than later I submitted this issue and now it looks fast as hell...

I will reopen it, if needed again...:/

**Comment by gitblit** [comment]
Thanks, Tamas.  Keep us in the loop.

**Comment by tomposmiko** [comment]
Finally I received the required information from one of my dev:

```
$ git push
15:36:26.668140 git.c:349               trace: built-in: git 'push'
15:36:26.690726 run-command.c:351       trace: run_command: 'ssh' '-p' '9999' 'USER@HOSTNAME' 'git-receive-pack '\''/plexus-suite/frontend.git'\'''
15:39:08.473020 run-command.c:351       trace: run_command: 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
15:39:08.473843 exec_cmd.c:130          trace: exec: 'git' 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
15:39:08.477525 git.c:349               trace: built-in: git 'pack-objects' '--all-progress-implied' '--revs' '--stdout' '--thin' '--delta-base-offset' '--progress'
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 490 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: Resolving deltas: 100% (4/4)
remote: Updating references: 100% (1/1)
To ssh://HOST@USER:9999/plexus-suite/frontend.git
   6b6186e..9309352  NPS-5038-share-with-all-users -> NPS-5038-share-with-all-users
```

Does it help?

**Comment by paulsputer** [comment]
Looks as though the time is spent when running ssh, I wonder if it's related at all to #1001.  Perhaps the server side logs will reveal some more info.

**Comment by tomposmiko** [comment]
I can see really nothing special in the server logs. Maybe if I increase the verbosity, but it's not that easy, because the issue come up rarely.
Do you suggest to do that?

**Comment by flaix** [comment]
Hi Tamas,

for the record, is this closed because the issue hasn't come up anymore or because you stopped using Gitblit altogether?
