### ISSUE TITLE
Compiling / Modifying for Android

### ISSUE THREAD

**Issue by szquadri** [gitblit/gitblit#1017]
I am wondering how much issues or pain point will it be to compile gitblit for running on latest android versions. 

We already use and love gitblit, but prospect of using an Android device as fully functional git server is beyond awesome. This is all java project and uses bits of AOSP code and at least we can think in that direction.

Can community or @gitblit kindly give some info or pointers?

**Comment by gitblit** [comment]
Running on Android was something I did consider a couple years ago.  I suppose if you had a device with enough horsepower and ram it could be worthwhile.  But I expect the performance would be disappointing and certainly it wouldn't scale which would make the effort more of a gimmick than anything else.

Now, if Android infiltrates the desktop (and there are indicators that it might) then it might be worth more serious consideration.

**Comment by szquadri** [comment]
Thank you for the consoling update. At least I can expect Android compatibility in future when more powerful or server grade hardware for Android will be order of the day.

Will be keeping a tab on developments and will always be willing to contribute if I can.
