### ISSUE TITLE
Gitblit server is consuming a lot of CPU and memory grow

### ISSUE THREAD

**Issue by francisreat** [gitblit/gitblit#1029]
I use Giblit server 1.6.0.

it use authentification ldap (and Ldap sync service update users and groups every 3600000 minutes).
all the time the server uses between 40 and 50% of cpu and memory always increases. it
seems to have a memory leak...
The users.conf file is updated every minute although the sync is complete 3600000 minutes. is that this is normal  or that is the reason of the consumption of memory oand CPU ?
how I can fix the problem

Best regard

attached files : temp .zip with stdout.log and  gitblitproperties files

**Comment by francisreat** [comment]
Here attachments : 

[gitblitproperties.txt](https://github.com/gitblit/gitblit/files/187578/gitblitproperties.txt)
[gitblit-stdout.2016-03-24log.txt](https://github.com/gitblit/gitblit/files/187581/gitblit-stdout.2016-03-24log.txt)

**Comment by francisreat** [comment]
I closed this file by mistake....

**Comment by paulsputer** [comment]
Hi @francisreat, I'm using ldap to authenticate around 50 users from a 20K+ user ldap database and all works smoothly with no memory growth.  I get a feeling this isn't ldap related

### High git usage
The most probable cause for what you're seeing: your log file has an unusually high rate of git-upload-pack entries starting `ARF: CHALLENGE`.  I wouldn't expect these every second as soon as gitblit is operating until the moment it is shutdown.   Are you performing load testing or backups? 


### comparing ldap specific configuration:

*  realm.ldap.synchronize = true
Unless almost all your ldap users are using Gitblit or you are using ldap to manage teams via `realm.ldap.maintainTeams = true` I probably wouldn't enable this.  Apart from populating the user accounts initially what do you gain by leaving it on?  If this is set to `false` then when a user signs in for the first time you will then see their user account listed.

* realm.ldap.accountBase*
Depending on your configuration you may have a large number of non-user accounts in ldap that would never need access to gitblit, you may want to filter these out by defining a more precise accountBase.  A tool such as ADExplorer can come in very useful for identifying a suitable path.

**Comment by francisreat** [comment]
I installed the version 1.7.1 of gitblit, and the problem seems to have disappeared....

I still watch my server a few days and I close the ticket

**Comment by fzs** [comment]
@francisreat, can this ticket be closed?
