### ISSUE TITLE
Update to JGit 4.5

### ISSUE THREAD

**Issue by paulsputer** [gitblit/gitblit#1030]
[JGit 4.2](https://projects.eclipse.org/projects/technology.jgit/releases/4.2) release supports GitLFS, this could allow mirroring of repositories using LFS and provide a means for handling LFS files during federation requests.

Will need to determine the most appropriate route to integrate with GitBlit's LFS implementation.

**Comment by fzs** [comment]
I'm changing the issue to update to JGit 4.5, so that Gitblit would use the latest JGit version that still has Java7 as minimum requirement before it got changed to Java8 with version 4.6.

**Comment by softboy99** [comment]
1 year past,what is the status?

**Comment by fzs** [comment]
Closing this as Done.
GitBlit was updated to JGit in eaaf99e188ecefbd589fe08fd3b7652190258379.
The LFS implementation stays the same, using the GitBlit one.
