### ISSUE TITLE
packedGitOpenFiles doesn't changed

### ISSUE THREAD

**Issue by simbadltd** [gitblit/gitblit#1049]
Hi! I've tried to change git.packedGitOpenFiles parameter in gitblit.properties from 128 to 1024 and there is no effect:
"
include = defaults.properties

git.acceptedPushTransports =HTTP
git.repositoriesFolder = D:/gitblit-repos
git.packedGitWindowSize = 16k
git.packedGitLimit = 8g
git.streamFileThreshold = 2047m
git.deltaBaseCacheLimit = 50m
git.packedGitOpenFiles = 256
"

I can see only "RepositoryManager:1933 - git.packedGitOpenFiles = 128" in the log.

Another git parameters (like packedGitWindowSize and streamFileThreshold ) have been applied successfuly.

**Comment by gitblit** [comment]
Thanks for the report.  The wrong settings method was used to retrieve this value from the settings.
