### ISSUE TITLE
UI issue on storing or deleting ssh-keys

### ISSUE THREAD

**Issue by phormanns** [gitblit/gitblit#1057]
It possible to add or delete additional ssh-key in the user profile.

But there is no feedback to the user when he pushes the "Löschen" or "Hinzufügen" button. I would expect a page reload. After a manual page reload, the new ssh-key is shown.

**Comment by flaix** [comment]
I cannot reproduce this anymore. So I guess it was fixed by now. I can see feedback just fine when adding or removing a SSH key on the user's profile.
Closing this as obsolete.
