### ISSUE TITLE
RequestHeader set X-Forwarded-Context /gitblit does not affect repositoryURL in Website

### ISSUE THREAD

**Issue by olbohlen** [gitblit/gitblit#1058]
Hello, this *might* be a duplicate of:  Barnum (pt) download link is incorrect for war deployment #898 

I have gitblit GO behind a Apache 2.2 webserver with mod_proxy. I have set 
RequestHeader set X-Forwarded-Context /gitblit
as I need to run different services on this vhost.
This works fine so far, but when I open a repository on the gitblit WebSite and look for the git repository URLs, I miss the "/gitblit" part. 
I see
https://user@gitp.xyz.dom/r/testproj/test123.gi

but it should be:
https://user@gitp.xyz.dom/bitblit/r/testproj/test123.gi

**Comment by gitblit** [comment]
Odd.  The url generation supports `X-Forwarded-Context`.

**Comment by olbohlen** [comment]
![screenshot-gitp-wrong-url](https://cloud.githubusercontent.com/assets/16251171/14676246/f611e58a-070c-11e6-8e86-3bf1244e73b6.png)

**Comment by gitblit** [comment]
Huh.  What if you set `X-Forwarded-Proto` or `X-Forwarded-Port` ?

**Comment by olbohlen** [comment]
This is the section in my apache ssl.conf vhost:

ProxyPass /gitblit http://localhost:8080/gitblit
ProxyPassreverse /gitblit http://localhost:8080/gitblit
Header edit Location ^http://([^/]+)/gitblit/ https://$1/gitblit/
RequestHeader set X-Forwarded-Proto https
RequestHeader set X-Forwarded-Port 443
RequestHeader set X-Forwarded-Context /gitblit
AllowEncodedSlashes NoDecode

**Comment by olbohlen** [comment]
fixed it, no bug - but a configuration issue: forgot to specify the /gibtlit part in the web.canonicalUrl parameter

Sorry for this issue,

Olaf
