### ISSUE TITLE
Certificate file path printed in log files

### ISSUE THREAD

**Issue by rcaa** [gitblit/gitblit#1064]
GitblitServer.logger.error("Error parsing " + certificatesConf, e);

In the case an error occurs the line above is executed. The cerfificatesConf variable holds sensitive data. Thus, we should avoid passing it to logger, even as a String, which prints its path.

**Comment by gitblit** [comment]
Hi @rcaa.  Thanks for the report.  Perhaps you'd be willing to submit a PR?

**Comment by fzs** [comment]
@rcaa, which data do you consider sensitive? The `certificatesConf` is the path of the base folder, with `certs/authority.conf` appended. The path of the base folder is printed at startup anyway. The path for the `authority.conf` file is a public constant. What attack vector do you see in printing the combined path in the log upon error?

**Comment by rcaa** [comment]
@fzs I reckon this path should not be printed at startup since authority.conf contains sensitive data. Attackers might get this path and try to maliciously use authority.conf. What is the purpose of printing this path at startup? Shouldn't we avoid it?

**Comment by gitblit** [comment]
If an attacker is mining your log files, then you have a whole new set of problems.

**Comment by fzs** [comment]
The `authority.conf` file doesn't contain any sensitive data. It contains the DN data for the certificate's subject name. Which is public information.

It's path is printed when an error happens, which is beneficial for analysis. Printing the path of the base folder on start up is also done to have that information ready when something is not working as expected as it is a common source of errors when upgrading. That path is printed in a few error messages, too, I believe.

What you might actually be commenting on is, that the location of the key store can be gleaned from that. But I think that is not a real problem and the benefits during analysis outweigh the drawbacks on a lazily set up system. If security is a concern for a Gitblit installation, then the proper way is to have the key store only accessible to the Gitblit server through operating system means. Not printing a path in a log will not help here.

I would therefore consider this a non-issue.

**Comment by gitblit** [comment]
I agree with Florian's assessment. Not an issue, closing.
