### ISSUE TITLE
Milestone without due-date makes Gitblit stop serving tickets

### ISSUE THREAD

**Issue by QuentinC** [gitblit/gitblit#1069]
I've experienced an issue when a milestone is created without a due-date.
As soon as it's created, I cannot anymore access the tickets page.

The logs are showing that the error is there:  ([Github page](https://github.com/gitblit/gitblit/blob/master/src/main/java/com/gitblit/wicket/pages/TicketsPage.java#L524))

`
public int compare(TicketMilestone o1, TicketMilestone o2) {
	return o2.due.compareTo(o1.due);
}
`
The error is that the due-date is null, so I have a NullPointerException !

The only way to fix this is to manually edit the repository configuration to add the missing date !

You should maybe only verify that the date is correct, or allow empty date !

Thanks !

**Comment by paulsputer** [comment]
Hi @QuentinC could you confirm what browser and GitBlit version you're using?  I'm unable to replicate this on the current head c585040e2ea0f57ef2bfd50c6339fdbe2ec47522

**Comment by QuentinC** [comment]
I will try this, but I need to setup my dev environment before...

I should return back to you before the end of the week !


________________________________
De : Paul Martin <notifications@github.com>
Envoyé : samedi 18 juin 2016 23:56
À : gitblit/gitblit
Cc : Quentin Canel; Mention
Objet : Re: [gitblit/gitblit] Milestone without due-date makes Gitblit stop serving tickets (#1069)


Hi @QuentinC<https://github.com/QuentinC> could you confirm what browser and GitBlit version you're using? I'm unable to replicate this on the current head c585040<https://github.com/gitblit/gitblit/commit/c585040e2ea0f57ef2bfd50c6339fdbe2ec47522>

-

**Comment by QuentinC** [comment]
Hello,


You are alright, I cannot reproduce the problem this this HEAD.


Thanks !


________________________________
De : Quentin Canel
Envoyé : lundi 20 juin 2016 11:26
À : gitblit/gitblit; gitblit/gitblit
Cc : Mention
Objet : RE: [gitblit/gitblit] Milestone without due-date makes Gitblit stop serving tickets (#1069)


I will try this, but I need to setup my dev environment before...

I should return back to you before the end of the week !


________________________________
De : Paul Martin <notifications@github.com>
Envoyé : samedi 18 juin 2016 23:56
À : gitblit/gitblit
Cc : Quentin Canel; Mention
Objet : Re: [gitblit/gitblit] Milestone without due-date makes Gitblit stop serving tickets (#1069)


Hi @QuentinC<https://github.com/QuentinC> could you confirm what browser and GitBlit version you're using? I'm unable to replicate this on the current head c585040<https://github.com/gitblit/gitblit/commit/c585040e2ea0f57ef2bfd50c6339fdbe2ec47522>

-

**Comment by paulsputer** [comment]
Glad to here, thanks for confirming.

**Comment by illusion911** [comment]
I'm running version 1.8.0 and tried using Chrome / Firefox, but I'm still experiencing this issue. 
While on version 1.7.1, I created a Milestone without due date, resulting in this error. I upgraded to version 1.8.0 because it should be resolved, but it isn't.

Maybe it is because I added the milestone in the older version. Is the fix to deny creating a milestone without due date? Because that would explain...

Anyway, we are currently blocked in our main repository in production.

**Comment by paulsputer** [comment]
Hi @illusion911 to get production operational your best course of action would be to log into your server, navigate to the git repositories and modify the repository config file that has a blank or missing due date.

It follows the ISO8601 format 
due = YYYY-MM-DD

I was unable to reproduce so if you can suggest a PR that resolves this for you that would be great.
