### ISSUE TITLE
Enable or disable ticket creation by repository

### ISSUE THREAD

**Issue by monkiki** [gitblit/gitblit#1075]
Hi,

I have a problem with the ticket settings. According to the documentation I can enable or disable ticket creation by repository but I only can disable or enable them globally. How is supposed to work? If I set tickets.acceptNewTickets to false, can I enable per repository? Or should I enable it globally and disable in each repository I don't want it to have this enabled?

I think this problem is related to #882 - **Honour disable ticket repository setting** but I'm not sure if it's exactly the same case.

**Comment by paulsputer** [comment]
Hi @monkiki yes there is an option for each repository go to edit repository -> tickets.

Prior to #882 disabling allow new tickets would disable patchsets and have no effect on tickets for the repository. This is now fixed and pending in the 1.8.0 release.

It has been merged in so you can build master if you need this capability quickly. 

You only need to disable the global setting if you wish to disable tickets for all repositories.

**Comment by monkiki** [comment]
So, in 1.8.0 I need to enable it globally and disable it in any repository I don't want tickets?

Do you have any plan to release this new version soon?

Thanks in advance! Very good piece of software :D

**Comment by paulsputer** [comment]
> I need to enable it globally and disable it in any repository I don't want tickets

That's correct

> Do you have any plan to release this new version soon?

Hopefully, currently soak testing to make sure #1048 is working as anticipated and provide ample opportunity for code reviews.  Also awaiting a fix for #964

**Comment by monkiki** [comment]
Thanks for the info. I will follow these other tickets.
