### ISSUE TITLE
Non-commiting users in Responsible dropdown

### ISSUE THREAD

**Issue by walshta** [gitblit/gitblit#1077]
I'm a sole developer that started using GitBlit + Jenkins. I've got GitBlit setup so that the admin user creates and owns all the repositories and the jenkins user has RW+ to all repositories. This way my id is a standard user id with RWC, otherwise I can't create ticket branches, and can't make changes admin changes to the repo.

When I create a new ticket, I set the responsible user to my id. However the admin and jenkins id's show up in that dropbox. Would it be possible to add a user property that would disable id's from showing up as able to receive tickets?

**Comment by gitblit** [comment]
The Responsible list is based on push permissions.  Your Jenkins and Admin users have push permission to the repository so they are available choices.  I agree that this is noisy but I'm not sure we can change that behavior without causing harm to other installations.

**Comment by walshta** [comment]
I see your point. There isn't a clean way to add a role to every user in an existing installation without it causing disruption. A one time script that is given the option to run the first time an admin logs in would do the trick but then you have a one-off piece of code that is part of the login sequence.
