### ISSUE TITLE
I pushed some large iOS lib to server, I got a error info.

### ISSUE THREAD

**Issue by suntabu** [gitblit/gitblit#1082]
here is the log:
git push origin master
Counting objects: 82, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (78/78), done.
Writing objects: 100% (82/82), 112.65 MiB | 2.44 MiB/s, done.
Total 82 (delta 46), reused 0 (delta 0)
error: unpack failed: error Java heap space

How could I update the remote branch successfully?

**Comment by gitblit** [comment]
Sounds like you need to feed your JVM instance more memory.  You'll want to
investigate the -Xmx JVM launch parameter.​

**Comment by fzs** [comment]
@suntabu, have you been able to resolve your issue by setting a larger heap space for the JVM?

**Comment by fzs** [comment]
Closed for inactivity. Heap space can be increased in the JVM.
