### ISSUE TITLE
ldap user sync and seen on user.conf but user login  fail

### ISSUE THREAD

**Issue by dipenpatel235** [gitblit/gitblit#1085]
Hello..
I have did successfully did ldap setting and also seen my all user 
but when user login so it said  "Invalid User or Password" 

below is my gitblit.properties settings

realm.authenticationProviders = ldap
realm.passwordStorage = md5
realm.minPasswordLength = 5
realm.ldap.server = ldap://xxx.xxxxxxx.com:389
realm.ldap.username = cn=Directory Manager
realm.ldap.password = XXXXXXXXXX
realm.ldap.backingUserService = ${baseFolder}/users.conf
realm.redmine.backingUserService = ${baseFolder}/users.conf
realm.ldap.maintainTeams = false
realm.ldap.accountBase = DC=xxxxxxxx,DC=com
realm.ldap.accountPattern = (&(objectClass=person)(uid=${username}))
realm.ldap.displayName = displayName
realm.ldap.uid = uid
realm.ldap.synchronize = true
realm.ldap.syncPeriod = 5 MINUTES
realm.ldap.removeDeletedUsers = true

**Comment by fzs** [comment]
Closing as duplicate to #1099.
