### ISSUE TITLE
Build only from within workspace (don't use home directory)

### ISSUE THREAD

**Issue by robindegen** [gitblit/gitblit#1089]
Due to security settings in our Jenkins environment, we can not write outside of the workspace directory. This means that moxie fails trying to write ~/.moxie.

Is there a setting to overwrite this behavior so that everything can kept inside of the workspace directory? Or can this feature be added?

I'm seeing a hardcoded path to ```${user.home}/.moxie```.

We use gitblit regularly, and want to add it to our jenkins environment so that updating can be a bit more streamlined.

**Comment by gitblit** [comment]
Hi Robin,

If you launch Ant with a `-D` parameter you can relocate the `MX_ROOT`.  e.g. `-Dmx.root=/some/path/here`

https://github.com/gitblit/moxie/blob/master/toolkit/src/core/java/org/moxie/Toolkit.java#L97-L106

**Comment by robindegen** [comment]
@gitblit Thanks i'll try that

**Comment by robindegen** [comment]
@gitblit That worked. I ended up using:
```ant buildWAR -Dmoxie.dir=$(pwd)/moxie/```
