### ISSUE TITLE
ldap Invalid username or password!

### ISSUE THREAD

**Issue by dipenpatel235** [gitblit/gitblit#1099]
Hello...
i have configured ldap login.
successfully sync show user list of all admin user in admin > users

But when i am trying to login using that id so getting error "Invalid username or password!"

Please Help Me .

Thanks

**Comment by fzs** [comment]
@dipenpatel235, do you still have an issue or have you resolved it?

**Comment by dipenpatel235** [comment]
Yes still same issue

**Comment by fzs** [comment]
Okay, so let's try and figure this out. First, which version of Gitblit are you using?

To reiterate: you can log in to Gitblit with the local admin user account. You have configured LDAP synchronisation and you do see the users in Gitblit. You do not synchronize teams.

Make sure that you do not have `realm.ldap.bindpattern` set.
When you log in to Gitblit as a LDAP user, do you use the value that is stored in the `uid` attribute in LDAP?

You can enable debug output for LDAP on Gitblit if you start Gitblit with the following two parameters on the command line (or in the start script, depending on how you start Gitblit): 
`-Dcom.unboundid.ldap.sdk.debug.enabled=true -Dcom.unboundid.ldap.sdk.debug.level=INFO` (see #698).

You may also want to search the [Gitblit discussion group](https://groups.google.com/forum/#!searchin/gitblit/ldap%7Csort:relevance) for posts that might help you.

**Comment by fzs** [comment]
Closed due to inactivity.
