### ISSUE TITLE
Create a wicket 7 branch 

### ISSUE THREAD

**Issue by pingunaut** [gitblit/gitblit#1106]
We love gitblit and would like to extend usage, but we're a bit concerned about the old wicket version being used which is no longer supported. I invested quite some time to upgrade to the latest wicket (7.4.0)
but i do not dare to create a pull request to your master branch yet:
https://github.com/pingunaut/gitblit/tree/wicket-7

By now there are no more compile errors, resources are loaded properly, fragments are resolved, no more JavaScript errors. Dashboard-, repository-  and usermanagement-pages  are working. Unfortunately we do not use the ticket feature, so i did not have the chance to test that yet.

It would be great if you could create a wicket 7 branch so i can create a a pull request to it. 
That way others can easily join wicket-7 migration.

Regards,
Martin

**Comment by gitblit** [comment]
@pingunaut Branch created.  Thanks for tackling this.
