### ISSUE TITLE
how to create users account?

### ISSUE THREAD

**Issue by BitSums** [gitblit/gitblit#1112]
how to allow users to create an account?
That is, I want to they were recorded, and I'm not to register them.

At the gitlab it is done according to the standard:

![wj0lwhyskkixblwc0eksca](https://cloud.githubusercontent.com/assets/20419550/17513957/b5e2dd56-5e38-11e6-806c-150842d5ebc2.jpg)

**Comment by gitblit** [comment]
User sign up has not been implemented.

**Comment by BitSums** [comment]
Why?
It is planned?

**Comment by gitblit** [comment]
Many installs tend to integrate with external authentication like LDAP and PAM.  Some script the creation of the users.conf file.  The project is always looking for contributions.  Would you be interested in implementing this?

**Comment by fzs** [comment]
If you are interested in user signup, please open a new issue for a feature request so that it can be voted for and get traction.
