### ISSUE TITLE
HttpUtils getGitblitURL does not support nonstandard ports

### ISSUE THREAD

**Issue by j123b567** [gitblit/gitblit#1114]
We are using reverse proxy. Gitblit is running only HTTP on port 29080 and apache does reverse proxy to HTTPS 4000. 

It is caused by regression in pull request #1086, the solution of #1083.

It is because the port number is doubled. In the path, there is hardcoded check for 80 and 443, but there is no check if host already contains the port number.

With `web.canonicalUrl = https://ourhost:4000` graph image is generated as

```
<img src="https://ourhost:4000:4000/graph/?r=........"></img>
```

`web.canonicalUrl` should contain nonstandard port.
Setting just `web.canonicalUrl = https://ourhost` also does not work.

**Comment by dsteinkopf** [comment]
Yes, you're right - I didn't test with non-standart "outside" ports.
What solution do you propose? Extend the mentioned "if" to also check if "host" contains ":"?
Would you like to provide a fix / pull request?
