### ISSUE TITLE
How to manually reset password

### ISSUE THREAD

**Issue by samcov** [gitblit/gitblit#1123]
How would I manually reset all Gitblit passwords and start fresh without losing any repositories?

I searched stackoverflow with no success.

**Comment by gitblit** [comment]
There is no such function.  You'd have to manually edit `users.conf` and change the passwords manually.

**Comment by samcov** [comment]
That's my question, how do I edit users.conf manually if the passwords are encrypted?

**Comment by samcov** [comment]
Scratch that, I see that you can reset it using clear passwords, Thanks, that solves my problem.
