### ISSUE TITLE
AD/LDAP teams/groups are not synced

### ISSUE THREAD

**Issue by TamasSzerb** [gitblit/gitblit#1124]
In log I found:

2016-09-06 15:56:56 [INFO ] ----[com.gitblit.manager.IAuthenticationManager]----
2016-09-06 15:56:56 [INFO ] setting up com.gitblit.auth.LdapAuthProvider
2016-09-06 15:56:56 [INFO ] Ldap sync service is disabled.

but when logging in with given user, no issue experienced, successfully authenticated by checking the debug logs with 

com.unboundid.ldap.sdk.debug.enabled=true
com.unboundid.ldap.sdk.debug.level=ALL

sysprops.

The relevant config:

realm.authenticationProviders = ldap
realm.ldap.server = ldap://ldap:389
realm.ldap.username = cn=bind_user,ou=Service Accounts,ou=Users,ou=_Global,ou=CORP,dc=local,dc=example,dc=org
realm.ldap.password = XXX
realm.ldap.maintainTeams = true
realm.ldap.accountBase = dc=local,dc=example,dc=org
realm.ldap.accountPattern = (&(sAMAccountName=${username}))
realm.ldap.groupBase = OU=Distribution Groups,OU=_Global,OU=CORP,DC=local,DC=example,DC=org
realm.ldap.groupMemberPattern = (&(objectClass=group)(member=${dn}))
realm.ldap.admins = szertam @git_admins
realm.ldap.displayName = displayName
realm.ldap.email = mail
realm.ldap.ldapCachePeriod = 1 MINUTES
realm.ldap.synchronizeUsers.enable = true
realm.ldap.synchronizeUsers.removeDeleted = true
realm.ldap.uid = sAMAccountName

And of course I see no sign the synchronization activity. Any idea how to get it fixed?
Vanilla gitblit-1.8.0.war

Thanks,

Tamas

**Comment by gitblit** [comment]
try

    realm.ldap.synchronize = true

**Comment by TamasSzerb** [comment]
thanks, works well.
