### ISSUE TITLE
unable to find local git repo

### ISSUE THREAD

**Issue by hurnhu** [gitblit/gitblit#1127]
i have made a git repo on my gitblit server and commited files to it. now i can not find the files on the machine with the repo. where would these files be stored?

**Comment by gitblit** [comment]
I'm not following exactly what you did on your setup but it seems like either you are new to git or that you are using terminology incorrectly.

I am assuming...

1. *made a repo on my gitblit  server* == I created a repo using Gitblit
2. *I committed files to it* == I cloned the repo, committed files to my clone, and pushed my new commits to Gitblit

Gitblit stores the repos in `{baseFolder}/git/{project}/{repo}.git`.  The files that you committed & pushed will be named/identified by a SHA-1 hash and will not be *found* by scanning the filesystem by their filename.  The committed files may be loose (individual files named by SHA1 hash) or they may be packed (single file aggregate of multiple files).

Does that answer your question?

**Comment by fzs** [comment]
Closed due to inactivity.
