### ISSUE TITLE
Connection Errors when using self-signed SSL cert

### ISSUE THREAD

**Issue by RobertMcCoy** [gitblit/gitblit#1134]
Been trying to follow a few guides on modifying the certs for the server (I won't lie, I'm not too keen on certs and the whole setup) such as http://serverfault.com/questions/453959/gitblit-using-cert-for-ssl, but anytime I import a new keypair into the keystore and attempt to connect to the server I get 

Attackers might be trying to steal your information from <SERVER> (for example, passwords, messages, or credit cards). NET::ERR_CERT_INVALID

I have tried importing both p12 and pfx, both to no avail. I have also tried importing a generated cert into the serverTrustStore, thinking maybe it thought things were being spoofed. I want to clarify this cert is not generated through the "authority", but rather a self-published cert within our domain.

**Comment by paulsputer** [comment]
Hi Robert, this is normal for a self-published certificate. It is possible to get free certificates from a signed authority which would then avoid this type of message.  You may like to check out https://letsencrypt.org/

**Comment by RobertMcCoy** [comment]
This server is remaining 100% internal, and on our network, we have this certificate publication set to be automatically verified. I'm assuming it's a conflict between Gitblit Certificate Authority vs. our network Certificate Authority?

**Comment by gitblit** [comment]
If you are using a signed-cert from your own authority then you don't need the Gitblit CA.

Have you confirmed that the cert presented to the browser is the one signed by your internal CA?
Is your browser configured to trust your internal CA's root certificate?

**Comment by RobertMcCoy** [comment]
Yes. If I attempt to use that certificate only I get errors attempting to run Gitblit. What should be done with the certificate in this case then?

**Comment by gitblit** [comment]
I'll assume yes is the answer to the second question.  I'm interested in the error produced by "If I attempt to use that certificate only".  I would guess it has to do with the configured alias.  Maybe you can share the error.

**Comment by RobertMcCoy** [comment]
Hmm...I'm having issues replicating the error from before. I hate to be a burden, but can you give me a quick walkthrough of what I should be doing? Should I be generating the keyStore through the authority and then modifying the key-pair in the keystore? If I don't have a KeyStore generated the program appears to automatically generate one for me and use that as the default.

**Comment by gitblit** [comment]
Yes, that is how it behaves - autogeneration of a working self-signed cert.

If you have your own signed cert with the trust chain, collect all those certs (pem, crt, whatever extension) and use [KeyStore Explorer](http://www.keystore-explorer.org/) to create a new keystore.  Reconfigure Gitblit to use your new keystore and make sure to set the appropriate *server.certificateAlias* to the appropriate Keystore key name.  By default Gitblit looks for a certificate using the key name "localhost" - if that is not found then Gitblit may throw an exception.  Don't forget to also configure Gitblit with the passwords for your keystore and make the password for the cert match the password for the keystore itself.

**Comment by RobertMcCoy** [comment]
Still getting the invalid certificate error. I will just revert to the Gitblit Cert Authority way, I must be naming something wrong or issuing the certs incorrectly.
