### ISSUE TITLE
No auto pulling?

### ISSUE THREAD

**Issue by gerroon** [gitblit/gitblit#1158]
HI

I copied Blender`s git repo and added to GitBlit. However I see that GB does not pull remote changes automatically. I looked at the default properties and there is default 60 min pulling. I assumed that that is the one that does pulling but it is not working for me here. 

I am using WAR on Debian Wheezy 

/opt/gitblit-1.8.0# java -version
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) Server VM (build 25.73-b02, mixed mode

/opt/gitblit-1.8.0# git version
git version 1.7.10.4

**Comment by fzs** [comment]
Actually the default mirroring period is 30 minutes.
Did you enable `git.enableMirroring`? What is the setting of your `git.mirrorPeriod`?
Did you clone the original repository as a mirror using the `--mirror` option? What does your log output  say?

**Comment by gerroon** [comment]
Hi

I did not know about the mirroring. I will give it a try. 

thanks

**Comment by fzs** [comment]
Using mirrors is the official way to have Gitblit keep an mirror repository updated. You can read up on mirrors in the [Gitblit documentation](http://gitblit.com/setup_mirrors.html).
I'm not sure which other setting you thought would be for "auto-pulling", but chances are it was something unrelated.

**Comment by gerroon** [comment]
@fzs

Ok I tried everything you said and I am still not getting it updated. 

git clone --mirror git://git.blender.org/blender.git blender

All the settings related to the mirroring are set to what you recommended.

**Comment by fzs** [comment]
I tried your example and it seems to be working fine. So it looks like a problem with our setup.

Does your log show that the mirroring service is enabled?
```
2016-12-05 12:30:24 [INFO ] Mirror service will fetch updates every 10 minutes.
2016-12-05 12:30:24 [INFO ] Next scheduled mirror fetch is in 1 minutes
```
How do you know that it is not updating? You may want to try and enable [debug logging](http://gitblit.com/setup_go.html#H12), which would give you output like this:
```
2016-12-05 12:41:24 [DEBUG] checking blender remote origin for ref updates
2016-12-05 12:41:24 [DEBUG] mirror is skipping helloworld.git no mirror remote found
2016-12-05 12:41:24 [DEBUG] mirror is skipping myownstuff !mirror !bare
```
To only enable debug logging for the mirror service use the logger `com.gitblit.service.MirrorService`.

Have you checked if the directory access permissions for the blender mirror are correct so that your Gitblit instance can write to it?

**Comment by gerroon** [comment]
@fzs 
Thanks for the follow up. I will investigate it,

**Comment by fzs** [comment]
Were you able to get this to work, or are you still having trouble with it, @gerroon?

**Comment by fzs** [comment]
Closed due to inactivity.
