### ISSUE TITLE
Access `http://xx//`(double `/`) will list all files in gitblit.jar

### ISSUE THREAD

**Issue by yyjdelete** [gitblit/gitblit#1161]
Access `http://xx//`(double `/`) will list all files in gitblit.jar

Gitblit GO (Linux) 1.8.0 is used.

**Comment by gitblit** [comment]
Cool!  Maybe we can call that a feature. ;)

**Comment by fzs** [comment]
Do you see this as a problem?
It's rather easy to prevent, but I have no idea if disabling directory listing would have side effects, e.g. on LFS. So if it is just an oddity and nothing serious, we could leave it at this.
