### ISSUE TITLE
Name of repositories is case sensitive or not?

### ISSUE THREAD

**Issue by yyjdelete** [gitblit/gitblit#1162]
I create an repository `https://xxx/r/aa/test.git` and push to `https://xxx/r/Aa/test.git` by mistake.
Then I found that an new repository is created, but it's not listed in repositories list.

Should create and list repository follow the same rule for case sensitive?

Gitblit GO (Linux) 1.8.0 is used.

**Comment by gitblit** [comment]
Internally repo names are case-insensitive but case is respected on the filesystem. [docs](http://gitblit.com/administration.html#H3)
