### ISSUE TITLE
No commit diff highlighing in Chrome

### ISSUE THREAD

**Issue by samized** [gitblit/gitblit#1177]
After upgrade from version 1.6.2 to 1.8.0 the commit diff highlighting stopped working in browser Chrome. In Firefox everything looks like in version 1.6.2.

Screenshot Chrome 55.0.2883.87:
![gitblitdiffissue](https://cloud.githubusercontent.com/assets/2572223/21683961/f41039a0-d35b-11e6-85a2-10d19b7c1bce.png)

Screenshot Firefox 50.1.0:
![gitblitdiffissue2](https://cloud.githubusercontent.com/assets/2572223/21683982/0782037e-d35c-11e6-95d9-9c45408ea9e3.png)

**Comment by gitblit** [comment]
I'm running that version of Chrome on Windows and I can't reproduce.

**Comment by samized** [comment]
Ok, after some debugging I found the problem. It was a caching issue with chrome.
I don't know why this css resource wasn't reloaded even with multiple refreshes.
