### ISSUE TITLE
Tickets overview page is empty

### ISSUE THREAD

**Issue by martinrotter** [gitblit/gitblit#1179]
There are some tickets existing throughout many repositories. Some tickets are assigned to me, some are created by me, some by others.

But the tickets overview page "My Tickets" is empty, no matter what I do. I can click on "Reset", I can display "All" tickets, but still the list is empty.

EDIT: I think that it is related to fact, that filter button "repository: all" does not offer any repositories, which is not correct, because I have many repos active.

EDIT: I think that this is related to users logged in via WINDOWS authentication provider.

1. I log in as `domain\user`. I go to some repository, create ticket, assign it to myself.
2. I go to "My tickets" and ticket is not there.
3. Above two steps seem to produce correct behavior (ticket is in "My tickets") when logged in as local gitblit user.

It seems that tickets that are created by someone else and not assigned to me, are not visible by me. Is there a way to see absolutely ALL created tickets in "My tickets" page?

I believe that part of the core of the problem is here (`MyTicketsPage.java`):
````
        // general "my tickets"
        return qb.andSubquery()
                 .or(Lucene.createdby.matches(username))
                 .or(Lucene.responsible.matches(username))
                 .or(Lucene.watchedby.matches(username))
                 .or(Lucene.mentions.matches(username))
                 .endSubquery();
````

**Comment by fzs** [comment]
If you didn't create the ticket and it is not assigned to you (and you are not watching or participating in that ticket), then it does not belong to "your" tickets. So it isn't visible on your My Tickets page.

**Comment by martinrotter** [comment]
If I am logged via Windows provider then even tickets created by me are not visible in my tickets.

**Comment by martinrotter** [comment]
I mean, If i log in via username `DOMAIN\user`, then tickets created by that user are not visible in his "My tickets". Local gitblit accounts work OK.

**Comment by fzs** [comment]
I see. In that case this is because there is a deficiency in Windows login handling in Gitblit. If you log in with domain\user than that will be a different user within Gitblit than your local account. See also issue #1079.

Again, the My Tickets page is a page that lists all tickets _of the one user being logged in_, meaning tickets created or assigned to him, tickets he is watching or mentioned in. Since it will be a different user when you login with domain\username than when you log in with username, tickets of one will not show up on the page of the other.

**Comment by martinrotter** [comment]
#1079 might be really connected to my problems. I reverted to only using LOCAL accounts in our company as with local accounts, we have now problems.

**Comment by fzs** [comment]
Did you mean "with local accounts we have no problems" or "... we have now problems"?

**Comment by martinrotter** [comment]
I meant what I have written. Local accounts work without problems and all "my" tickets are really visible in "My tickets" page.

**Comment by martinrotter** [comment]
Is this solved?

**Comment by fzs** [comment]
Well, you said you have no problems with it, so I closed this issue.
If you are referring to issue 1079, then no, it is not solved. Since you seem to have the same problem, you may want to watch issue 1079.
Or do you have a separate issue here that I didn't understand?

**Comment by martinrotter** [comment]
I worked-around the issue. But there is no doubt, that there is existing bug in GitBlit. :) Indeed, I overlooked the issue #1079. I will check the status there.
