### ISSUE TITLE
How to migrate gitblit repos to new server

### ISSUE THREAD

**Issue by ansaj777** [gitblit/gitblit#1181]
How to migrate gitblit repos to new server? Is there any possiblity to do it?

**Comment by gitblit** [comment]
Aside from the obvious copying the data directory, you could try using federation to clone all the repos.

**Comment by ansaj777** [comment]
> Aside from the obvious copying the data directory, you could try using federation to clone all the repos.

How can I clone it?

**Comment by gitblit** [comment]
Have you reviewed [this](http://gitblit.com/federation.html)?

**Comment by chucklu** [comment]
@gitblit  

> git.enableGitServlet = true
> federation.passphrase = ybbu3Cn&NAu@4LJ
> federation.allowProposals = true

I have configured the federation，but I can not find the federation on web ui ，already signed in with admin account.
