### ISSUE TITLE
[Feature request] Add a way to display ALL tickets from ALL repositories in "My tickets" page.

### ISSUE THREAD

**Issue by martinrotter** [gitblit/gitblit#1182]
Perhaps add a button to remove all filters and display literally all tickets that exist throughout gitblit instance?

**Comment by fzs** [comment]
Well, it is the _My Tickets_ page. So it will list only tickets that are related in a way to a certain user. It doesn't make much sense to list tickets on that page, which have no connection to said user.

I believe this feature request is a duplicate of #821. While there should be a way to list all tickets, I don't think it should be the My Tickets page, which exists for a different reason.

**Comment by martinrotter** [comment]
Yes, It is not important if there is any other page or "My tickets".
