### ISSUE TITLE
Delete remote branch hangs

### ISSUE THREAD

**Issue by mystygage** [gitblit/gitblit#1189]
Since upgrading from 1.6 to 1.8 deleting a branch sometimes hangs.

```
~/Projects/repo master
❯ git push origin --delete featureBranch
remote: Updating references: 100% (1/1)
```

After `ctrl+c` and pushing the delete again, the branch is gone:

```
^C
~/Projects/repo master  5m 27s
❯ git push origin --delete featureBranch
error: unable to delete 'featureBranch': remote ref does not exist
error: failed to push some refs to 'https://gitblit/r/repo.git'
```

I checked the logs, but all I found was a hint of my push in stdout.log

```
2017-01-25 15:55:54 [INFO ] ARF: authenticated user to repo.git/info/refs?service=git-receive-pack (100)
2017-01-25 15:55:55 [INFO ] ARF: authenticated user to repo.git/git-receive-pack (100)
```

Any ideas how to get the cause of this problem?

**Comment by paulsputer** [comment]
@mystygage I've experienced this on occasions back on a 1.7.1 deployment but it appeared to coincide with an update of the git client.  Could this perhaps be the same for you?  I seem to recall there was a update done on the client file system cache (at least for windows version of git) not sure if it's related somehow.

**Comment by mystygage** [comment]
@paulsputer thanks for your feedback. I use git 2.11.0 on macOS.
I'm 99% sure that I updated git a week or two ago and that my problems with deleting branches started after upgrading to the newest gitblit version. I'll do a rollback to 1.6 and try this again.

**Comment by mystygage** [comment]
After downgrading to 1.6 the problem is gone. Perhaps this problem is also repository related, unfortunately I can't share this repository in a public place.

```
~/Projects/repo featureBranch
❯ time git push origin --delete featureBranch
remote: Updating references: 100% (1/1)
To https://gitblit/r/repo.git
 - [deleted]             featureBranch
git push origin --delete featureBranch  0.04s user 0.04s system 1% cpu 5.655 total
```

**Comment by gitblit** [comment]
Hmm.  Difficult to pinpoint.  There have been alot of dependency updates since 1.6.0.  Perhaps a JGit update introduced a regression.  Not sure.  Does it make a difference if you use this syntax?

`git push origin :featureBranch`

**Comment by mystygage** [comment]
I think it was somehow hardware related... We recently switched to faster hardware and I upgraded gitblit again to 1.8. Now everything works fine
