### ISSUE TITLE
Custom authenticator not loading

### ISSUE THREAD

**Issue by kontza** [gitblit/gitblit#1197]
Hi,

I wrote a custom authenticator for GitBlit and I've specified the class path in default.properties:
`realm.authenticationProviders = org.kontza.SoapAuthenticator`

I have my own jar in the same directory with the `gitblit.jar`-file and I'm trying to run GitBlit manually by `java -cp "soap-auth.jar:./*" -jar giblit.jar --baseDir data`.

I constantly get `java.lang.ClassNotFoundException: org.kontza.SoapAuthenticator`.

My _SoapAuthenticator_ is subclassed from _UsernamePasswordAuthenticationProvider_ as the docs say I should do.

Is my class path wrong or is the class implementation wrong?

```
public class SoapAuthenticator extends UsernamePasswordAuthenticationProvider {

    private final static Logger logger = LoggerFactory.getLogger(GitblitAuthenticator.class);

    public SoapAuthenticator() {
        super("SOAPAuthenticator");
    }

    public GitblitAuthenticator(String serviceName) {
        super(serviceName);
    }

    @Override
    public void setup() {
    }

    @Override
    public UserModel authenticate(String username, char[] password) {
        SOAPClientSAAJ client = new SOAPClientSAAJ(null);
        UserModel retVal = null;
        if (client.authenticate(username, new String(password))) {
            retVal = new UserModel(username);
        }
        return retVal;
    }

    @Override
    public Constants.AccountType getAccountType() {
        return AccountType.LDAP;
    }

    @Override
    public boolean supportsCredentialChanges() {
        return false;
    }

    @Override
    public boolean supportsDisplayNameChanges() {
        return true;
    }

    @Override
    public boolean supportsEmailAddressChanges() {
        return false;
    }

    @Override
    public boolean supportsTeamMembershipChanges() {
        return true;
    }

    @Override
    public boolean supportsRoleChanges(UserModel user, Constants.Role role) {
        return true;
    }

    @Override
    public boolean supportsRoleChanges(TeamModel team, Constants.Role role) {
        return true;
    }

}
```

**Comment by gitblit** [comment]
Drop your jar into the `ext` directory and start Gitblit GO normally.

**Comment by kontza** [comment]
Ok, thanks. 

Is this mentioned somewhere in the docs? I couldn't find it, although I must say that I only checked the authentication page, and the FAQ.

Could the docs be updated so that it would e.g. read:

>Please subclass com.gitblit.auth.AuthenticationProvider.UsernamePasswordAuthenticationProvider.
>
>You may use your subclass by specifying its fully qualified classname in the `realm.authenticationProviders` setting.
>
>_Your subclass must be on Gitblit's classpath and must have a public default constructor._
>
>**In case of GO-version, put the jar-file containing your subclass into the `ext`-directory.**
