### ISSUE TITLE
Hook script on tag pushed

### ISSUE THREAD

**Issue by ManniManfred** [gitblit/gitblit#1211]
hi,
is it possible to execute a script if a tag is pushed?

**Comment by gitblit** [comment]
- It's possible to execute a Groovy script which can test if a tag is pushed.
- It's possible to write a plugin that can test if a tag is pushed.

There is no explicit hook just for tags and you can not directly execute Bash or PowerShell scripts.

**Comment by ManniManfred** [comment]
ok thanks
