### ISSUE TITLE
Posting webhook notifications to my own server

### ISSUE THREAD

**Issue by dmitry-naumovich** [gitblit/gitblit#1233]
Hello everyone! Could you help me, please?

I need my gitblit config repo to POST webhook notifications to my http://myserver:port/monitor endpoint which is configured on my Spring Cloud Config Server which uses Spring Cloud Bus.
How can I push hook events to my Spring Cloud Config server?

I know I have to leverage groovy scripts and I've look through these existing scripts https://github.com/gitblit/gitblit/tree/master/src/main/distrib/data/groovy but I don't have an idea how to set up webhook to my own server and where should I place `gitblit.properties` file. 

Thanks in advance.

**Comment by dbywalec** [comment]
Please have a look on sample fisheye groovy script. This will do the job for you. You might only need to adopt your target URL.
Having prepared the hook script, assign the hook in repository configuration to "post receive" event.

**Comment by fzs** [comment]
Closing as done since no further feedback from author.
