### ISSUE TITLE
Associating Tickets with Commits

### ISSUE THREAD

**Issue by shadowfoxish** [gitblit/gitblit#1246]
My team uses Gitblit as our source control and we've recently started experimenting with the tickets feature. The biggest issue we've found is that you cannot associate a commit with a ticket directly from the UI. Most of the developers here use Windows and SourceTree and aren't particularly comfortable in the git command line. 

We use a gitflow style pattern, so we're cloning repos, making feature branches, then merging into a develop or master branch. We don't use forks in our process. 

It would be extremely helpful if the Gitblit UI had a way to create a ticket from a branch, then we can do merge requests and track code reviews more efficiently than emailing diff links to team members. We could also skip the barnum and commandline stuff and keep doing gitflow the way everyone is used to.

If there is a way to do this, and I just haven't found it, I'd love to hear it. 
If there isn't, I'd be happy to contribute to a new feature, with a little input of 'where to start'. Maybe even a plugin? (Is the UI pluggable?)

**Comment by gitblit** [comment]
The UI is partially pluggable.

If you don't hack on Gitblit, then you could...
1. Manually create a ticket
2. Push a branch named `ticket/N` where N is the id of the ticket.  The `ticket/N` branch may point to an existing branch but only changes pushed to the `ticket/N` branch would be considered.

If you do hack on Gitblit, then you could add some sort of *create ticket from branch* feature.  It would probably still need to conform to the `ticket/N` branch model as that is pretty core to the design, IIRC.
