### ISSUE TITLE
Repositories not showing up in the repository list

### ISSUE THREAD

**Issue by royjavelosa** [gitblit/gitblit#1249]
Hi Guys I am new to GitBlit and I do not know where to ask about this issue.
I have created a new repository inside gitblit.  I made my commit in my local repository and successfully pushed my local repo to the remote GitBlit server.  
When I login to my GitBlit acount I can see my repository inside my dashboard under the "Owned" tab on the right menu, but when I click the Repositories Tab on the top Menu my new repository is not visible in the Repository list.   Why is this so?  I beleive this behaviour only happens if the remote GitBlit repo is empty but I have successfully pushed to the GitBlit Server. What did I miss?

**Comment by gitblit** [comment]
Is it a personal repository?  i.e. ~username/TheRepo.git

There is a setting which controls whether personal repositories are
included on the main repo list.
web.includePersonalRepositories = false

-J

**Comment by royjavelosa** [comment]
Thanks for the clarification.  I ended up sticking with this default behaviour so public repositories wont clutter the teams public dashboard.
