### ISSUE TITLE
integrate gitblit with scrumwise

### ISSUE THREAD

**Issue by ajuarezdiesvi** [gitblit/gitblit#1264]
Hello,

I've been trying to integrate scrumwise with gitblit, as shown on the following page: https://scrumwise.helpscoutdocs.com/article/92-how-do-i-set-up-an-integration-to-my-source- control-tool

But I could not, since I can not find a way to create Webhooks in gitblit, could you help me?

**Comment by fzs** [comment]
This is done via Groovy push hooks in Gitblit. 
http://gitblit.com/setup_hooks.html
There are a few pre-configured hooks that come with Gitblit. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by flaix** [comment]
Closing as answered. Please reopen if questions remain.
