### ISSUE TITLE
Problem downloading the pom.xml file of guice-servlet/4.0-gb2

### ISSUE THREAD

**Issue by ittaiz** [gitblit/gitblit#1269]
Hi,
We have a tool that iterates through the dependencies of our projects and apparently gitblit is one of them. 
Our tool uses maven aether to iterate through the dependencies transitively and it fails on guice-servlet since it seems you have the pom.xml under an incorrect name.
It shows as pom.xml (https://github.com/gitblit/gitblit-maven/blob/gh-pages/com/google/inject/extensions/guice-servlet/4.0-gb2/pom.xml) and not as guice-servlet-4.0-gb2.pom which is how gb1 is named (https://github.com/gitblit/gitblit-maven/blob/gh-pages/com/google/inject/extensions/guice-servlet/4.0-gb1/guice-servlet-4.0-gb1.pom).
Any chance you can rename the files?
I can also send a PR to fix them

**Comment by flaix** [comment]
Ups, this has actually since long been fixed. (gitblit/gitblit-maven@0f1169d2cc13c27783e34198ffcdc2c5fc2e00b1)
