### ISSUE TITLE
gitblit 1.8.0 Creating a Private Repository Can not Be Displayed

### ISSUE THREAD

**Issue by felix-ma** [gitblit/gitblit#1273]
There is a '~' sign on the front of the default folder that users display when they create their own private repository. Resulting in the display of the repository can not display all the items under this folder

**Comment by gqqnbig** [comment]
There is "owned" link on the home page. You will see your private repo there.

Also you can config `web.includePersonalRepositories`. Learn more at http://gitblit.com/properties.html

**Comment by fzs** [comment]
I don't think I understand the original question. But it seems solved.
For future reference, the prefix for the personal user repositories can also be changed when setting up Gitblit (`git.userRepositoryPrefix`).
