### ISSUE TITLE
I am unable to integrate ldap with glitblit.

### ISSUE THREAD

**Issue by Gopivadlapti** [gitblit/gitblit#1279]
Currently I am using 1.8.0. I configured ldap detail in the gitblit.config

realm.ldap.server = ldap://domain:368
realm.ldap.username = CN=SCMControls,OU=Machine Accounts,OU=Users,OU=place,OU=companyx,OU=na,DC=na,DC=domain,DC=com

realm.ldap.password = xxxxxxxxx

realm.ldap.bindpattern = CN=${username},OU=Users,OU=place,OU=na,DC=na,DC=domain,DC=com

realm.ldap.maintainTeams = false

realm.ldap.accountBase = dc=na, DC=domain,DC=com

realm.ldap.accountPattern = (&(objectclass=inetorgperson)(cn=${username}))

realm.ldap.groupBase = 

realm.ldap.groupMemberPattern =  (&(objectClass=groupOfUniqueNames)(uniqueMember=uid=${username},ou=na,dc=lennoxintl,dc=com))

realm.ldap.groupEmptyMemberPattern = (&(objectClass=group)(!(member=*)))

Above are the ldap config details.Right now I getting invalid user or password error.

It would be great, if help to turn around this issue.

Regards,
Gopi.

**Comment by AmishP** [comment]
@Gopivadlapti What do you have for the following value realm.authenticationProviders ?

**Comment by AmishP** [comment]
@Gopivadlapti are you still having a problem with this? If you have fixed it then please close the issue.

**Comment by flaix** [comment]
Closing issue as stale.
