### ISSUE TITLE
raw view of file of a branch with slash in there name failed

### ISSUE THREAD

**Issue by Krozark** [gitblit/gitblit#1290]
Version : 1.8.0

How to reproduce:
Create e repertory named repo/test
create a file "README.md" in the master branch, and push it 
create a branch named "feature/whatever"
create another empty file, and push it (just to create a commit)

Control:
On the web interface :  repo/test > branch "master" > last commit : tree > README.md : raw    : This should work

Trouble:
On the web interface :  repo/test > branch "feature/whatever" > last commit : tree > README.md : raw    : This should not work and we get a message like 

    Error
    Sorry, the requested resource ./README.md was not found in feature/whatever.

However, if we make the exact same procedure on the previous commit, it's ok (repo/test > branch "feature/whatever" > previous commit : tree > README.md : raw).

Also, notice that only branch with "/" (slash) in there name are concerned

**Comment by flaix** [comment]
I assume the "exact same procedure on the previous commit" means in this case essentially running it on the `master` branch. Therefore the problem only appears on a branch with a slash in the name. If the branch has no slash in the name, it works. It also works for files which are in subdirectories, so a slash in the filename is not a problem either. Only in the branch name.
