### ISSUE TITLE
Authentication > LDAP documentation not accurate

### ISSUE THREAD

**Issue by legenm** [gitblit/gitblit#1295]
Part

realm.ldap.username | cn=Directory Manager | The credentials that will log into the LDAP server

Should be changed to 

realm.ldap.username | **dn**=Directory Manager | The credentials that will log into the LDAP server

As it is working with DN attribute, not with CN.

**Comment by fzs** [comment]
The property value is the *DN* of the user/account/node with which GitBlit will log in to the LDAP directory to search for users and groups. That DN could be `CN=Directory Manager`. But it can be whatever is appropriate for the respective directory. A better example would probably be `CN=Directory Manager,DC=MyDomain`.
