### ISSUE TITLE
 generate an SSL certificate for  ip address hostnames needs graphical interface

### ISSUE THREAD

**Issue by maroodb** [gitblit/gitblit#1296]
Hello I want to generate ssl certificates on my linux server using the console mode without a graphical swing interface,

How to deal with that ?

**Comment by fzs** [comment]
That is possible with the `openssl` program.
There are ample websites available describing how to proceed, when you google for "openssl create certificate".

Here are two examples:
https://stackoverflow.com/questions/10175812/how-to-create-a-self-signed-certificate-with-openssl
https://www.thenativeweb.io/blog/2017-12-29-11-51-the-openssl-beginners-guide-to-creating-ssl-certificates/
