### ISSUE TITLE
Is it possible to public the Gitblit artifact to Maven Central?

### ISSUE THREAD

**Issue by reynoldsm88** [gitblit/gitblit#1301]
Adding the repository to settings.xml isn't a problem normally, however, sometimes at some customers we are not able to to access any external repositories directly. It is sometimes cumbersome to get the team maintaining their Artifactory or Nexus to agree to mirror a new repository. Was wondering what your thoughts were on publishing GitBlit to Maven central?

**Comment by fzs** [comment]
I am curious: what is your use case here?

**Comment by andrm** [comment]
Can't speak for the original question, but I use it for unit tests. Currently the com.gitblit:gitblit:1.8.0 artifact from an internal repository. Works well.

**Comment by andrm** [comment]
Sorry, we're using the repo at http://gitblit.github.io/gitblit-maven/

**Comment by fzs** [comment]
Use it for unit tests?
I wonder which GitBlit artifacts are useful in a Maven repo and for what. Like, developing a plugin?

**Comment by andrm** [comment]
yes, and integration tests when using gbapi. One can also start the gitblit server programmatically, like in a fatjar.

**Comment by fzs** [comment]
Sounds cool.
Sorry, I didn't see that you mentioned the gitblit artifact in your comment above. I take it that you also use the gbapi one when you are developing against the API.

I don't have an answer to the original question. I don't know how much work it is to get artifacts approved for Maven Central and what James is willing to put into it.

I am intrigued by the original question, though, what the use cases of @reynoldsm88 are, as he mentions customer sites.

**Comment by andrm** [comment]
For me the github.io site is sufficient. Would you be able to update it? Looks like a moxie generated thing.

**Comment by fzs** [comment]
No, that is a different GitHub project/repository.

**Comment by reynoldsm88** [comment]
I think the reason I originally asked was because we were attempting to resolve the artifacts from an internal closed Maven repo that was set up to mirror only Maven Central. Therefore, if we wanted to use GitBlit we would have to ask that team to whitelist a repository and they were not likely to do it for one artifact.

You can close this if you want we don't require it anymore.

**Comment by fzs** [comment]
Just out of interest, that was also to build something against Gitblit?
I am wondering if anyone would get the WAR from the maven repo in order to set up a Gitblit repo server.

**Comment by andrm** [comment]
In my opinion WAR distributions are legacy. Most momentum seems to be in standalone or embedded deployments.

**Comment by andrm** [comment]
BTW @fzs thank you ver much for your work on gitblit!

**Comment by fzs** [comment]
Oh, now it just gets embarrassing. :) Why, thank you, but its really not much, I don't really have a lot more time than James. I just like the project.

It is nice to hear that there is still interest in it. As far as I am concerned, the code is ready for a 1.9.0 release. If you have a server set up and want to, you could build it from the master and give it whirl.

**Comment by fzs** [comment]
Closing as obsolete
