### ISSUE TITLE
Antivirus report httpcore-4.3.3

### ISSUE THREAD

**Issue by michaljakubowski** [gitblit/gitblit#1302]
Hi,

my antivirus report that httpcore-4.3.3.jar is Html.Malware.Agent-6625209-0. Is it false positive or something maybe wrong with my version and I should check it? As I see control sum is like in file on webpage.

Regards,
Michal

**Comment by flaix** [comment]
This pretty sure was a false positive. But since the `httpcore` dependency has been updated to version 4.4.4, I am closing this as Done/Obsolete.
