### ISSUE TITLE
Authentication is required but no CredentialsProvider has been registered

### ISSUE THREAD

**Issue by haiguang0619** [gitblit/gitblit#1303]
when the project started,there is an error as
Error: https://github.com/git/hello-world.git: Authentication is required but no CredentialsProvider has been registered

who can help me ? thand you!

**Comment by fzs** [comment]
You may want to describe more what you are doing and what the output is.
Are you starting an installed instance or are you trying to run the test suite?
If the latter is the case, then an update to the current master could help.

**Comment by fzs** [comment]
Closing as Stale, no further feedback received.
