### ISSUE TITLE
State of Moxie tool?

### ISSUE THREAD

**Issue by chirontt** [gitblit/gitblit#1313]
Moxie seems to throw exceptions when trying to build the docs, like when you execute the command to build the Gitblit WAR file:

`ant buildWAR`

and exceptions are numerous from the MxDoc class:

buildWAR:
     [echo] Building Gitblit WAR 1.9.0-SNAPSHOT
    [delete] Deleting directory D:\dev\tmp\gitblit\build\war
   [mx:doc] =========================================================
   [mx:doc] mx:Doc  (Gitblit)
   [mx:doc] ---------------------------------------------------------
   [mx:doc] compiling and minifying D:\dev\tmp\gitblit\build\war\WEB-INF\docs\bootstrap\css\bootstrap.css...
   [mx:doc] css generated in 3,922 msecs
   [mx:doc] Generating HTML header...
   [mx:doc] Generating HTML footer...
   [mx:doc] Generating Structured Documentation from source files... 
   [mx:doc]    siteindex.mkd => index.html
   [mx:doc] Failed to transform siteindex.mkd
   [mx:doc] java.lang.RuntimeException: Error creating extended parser class: null
   [mx:doc] 	at org.parboiled.Parboiled.createParser(Parboiled.java:58)
   [mx:doc] 	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:92)
   [mx:doc] 	at org.pegdown.PegDownProcessor.<init>(PegDownProcessor.java:61)
   [mx:doc] 	at org.moxie.utils.MarkdownUtils.transformMarkdown(MarkdownUtils.java:51)
   [mx:doc] 	at org.moxie.utils.MarkdownUtils.transformMarkdown(MarkdownUtils.java:40)
   [mx:doc] 	at org.moxie.Docs.transformMarkdown(Docs.java:738)
   [mx:doc] 	at org.moxie.Docs.generatePages(Docs.java:431)
   [mx:doc] 	at org.moxie.Docs.execute(Docs.java:148)
   [mx:doc] 	at org.moxie.ant.MxDoc.execute(MxDoc.java:350)
...
   [mx:doc] Caused by: java.lang.IllegalStateException
   [mx:doc] 	at org.objectweb.asm.tree.ClassNode.<init>(ClassNode.java:197)
   [mx:doc] 	at org.parboiled.transform.ParserClassNode.<init>(ParserClassNode.java:41)
   [mx:doc] 	at org.parboiled.transform.ParserTransformer.extendParserClass(ParserTransformer.java:43)
   [mx:doc] 	at org.parboiled.transform.ParserTransformer.transformParser(ParserTransformer.java:38)
    [mx:doc] 	at org.parboiled.Parboiled.createParser(Parboiled.java:54)
    [mx:doc] 	... 39 more

Same exceptions are thrown when trying to run the `buildGO` and `buildSite` targets.

How did the gitblit 1.8.0 version get created then in 2016?

**Comment by fzs** [comment]
This is due to an update of JaCoCo in commit 23072ffb.
It can be reverted, like I did in fzs@b8373e4, but then running the tests doesn't work on Java8 anymore, or rather, running them with code coverage. 
So right now there is no one fix to have docs, coverage, Java 7 and 8.

**Comment by chirontt** [comment]
The problem can be resolved by explicitly adding the parboiled-java dependency to the Ant runtime classpath, into build.moxie:

`- build 'org.parboiled:parboiled-java:1.1.7'`

so that your revert can be avoided. Now gitblit can be built and tested by both JDK7 & 8.

**Comment by fzs** [comment]
👍 Fixed. Thank you.
