### ISSUE TITLE
realm.ldap.server with mutliple URLs possible?

### ISSUE THREAD

**Issue by thomass4t** [gitblit/gitblit#1326]
Hello,
we are using LDAP authentication in a Windows AD environment.
Everything works but we have several domain controllers and want to have a resilience regarding downtimes.
The parameter "realm.ldap.server" takes one URL as far as I read in the documentation.
Is is possible to configure multiple URLs for failover reasons?
e.g. if URL #1 is not reachable, try URL #2 etc.?

Thank you in advance,
Thomas

**Comment by fzs** [comment]
No, the parameter can only take one server. Listing multiple servers for distributed or fallback lookups is not implemented.
