### ISSUE TITLE
README content not being displayed on the summary page

### ISSUE THREAD

**Issue by paulobaumann** [gitblit/gitblit#1327]
My repository is managed by Gitblit, version 1.8.0. I have a file named _README.md_ in the root folder of the repo. In both _gitblit.properties_ and _defaults.properties_ there is the following line:
`web.summaryShowReadme = true`

However, the content of the README.md is not being displayed anywhere. What might be happening? How to fix it?

**Comment by fzs** [comment]
I could not reproduce this. I created a new repository via the Admin panel.
I initialised a new git repository locally, added a `Readme.md` file, added the Gitblit repo as a remote and pushed the initial commit.

The Readme shows up under the `docs` tab on the repository page in Gitblit.

Could you provide more information? Is there anything in the logs?

**Comment by paulobaumann** [comment]
Not only the *readme.md* page wasn't loading, but also any other internal links worked. For example, a link to a ticket in the description of another ticket pointed to the wrong host (`https://localhost:8443/...`) instead of the configured one (`https://10.0.0.12:8443/...`).

The following was set: `web.canonicalUrl = https://foobar:8443` and this address corresponded to `https://10.0.0.12:8443`. To load the repository portal, we used `https://10.0.0.12:8443`. 

Our sysadmin solved the issue changing the GitBlit instance to another server, and using an IP instead of a domain name in the `web.canonicalUrl` parameter.
