### ISSUE TITLE
Roadmap and release plan

### ISSUE THREAD

**Issue by srbala** [gitblit/gitblit#1329]
@fzs I see lots progress in the project. Is there any roadmap for current development and release plan soon?

**Comment by fzs** [comment]
Hi Bala,
the code for release 1.19.0 is done. I am currently working on updating the release script, switching to GitHub for building the release and deploying the binaries. James doesn't have the time to work on the releasee right now, so I am doing what I can. You should see a version 1.19.0 released soon. 

I don't have a roadmap, going forward. The closest thing to a roadmap would be the plan to drop support for Java 7, update the dependencies to the latest versions and review and merge existing PRs. And also switch away from Moxie as the build system, as that is not updated any more, gets in my way and a more commonly used one like Maven would benefit contributors, I think. So mainly things mentioned in other issues expressing interest in the project's state.

With a new, automated release process, my hope is also that I can (if my free time permits) release smaller increments more often.

**Comment by fzs** [comment]
Binaries are available by now on GitHub's releases page, by the way.

**Comment by srbala** [comment]
@fzs Florian, thanks for update and all the great work to release newer version. I see gh-pages were updated, but website still points to older release. I have updated docker release, when you have time please review and merge. https://github.com/gitblit/gitblit-docker/pull/8
