### ISSUE TITLE
gitblit.com still linking to v1.8.0

### ISSUE THREAD

**Issue by Barbiero** [gitblit/gitblit#1331]
Just a heads up since 1.9.0 was released about a month ago, I figure gitblit.com should be updated accordingly

**Comment by fzs** [comment]
Yes, unfortunately James has so far not found the time to either update the website, or have the domain/URL point/redirect to the [Github pages](https://gitblit.github.io/gitblit/).

**Comment by Barbiero** [comment]
Oh I wasn't aware of the GitHub pages. I'll direct people there when
needed. Thanks.

**Comment by fzs** [comment]
gitblit.com is now forwarding to the GitHub.io pages. Thanks James! 🎉

**Comment by fzs** [comment]
Actually, only the frontpage forwards to the Gihub pages with a refresh. Direct links to other pages will still end up on the old version.

I guess a overall 302 redirect for all paths would be better? Or maybe have the domain directly point to Github? I noticed that the subdomains are already A records.

**Comment by TDesjardins** [comment]
Also the link to full release notes (Github Gitblit releases page) points to http://gitblit.com/releases.html#1.9.2 which is confusing because last version of the old page is 1.8.0.
Maybe it makes sense to change it to https://gitblit.github.io/gitblit/releases.html#1.9.2

**Comment by flaix** [comment]
Uh, yeah, that is a problem.
To be honest I would still like to keep everything under gitblit.com, or at least one domain, instead of spreading it out with direct links here and there. I'll see if I can kick James again to setup a proper forwarding or find a way to deploy the pages again.
