### ISSUE TITLE
Manifest Change in 1.9.0 Requires Explicit Classpath

### ISSUE THREAD

**Issue by davehofmann** [gitblit/gitblit#1333]
First of all thank you very much for the development of Gitblit, it's a really nice software :)

I was just helping a colleage to update Gitblit GO on a FreeBSD server from 1.8.0 to 1.9.0. We ran into problems regarding a change in `MANIFEST.MF` in `gitblit.jar`. Since the issues are Java-related, they most likely apply for all operating systems.

The manifest from 1.8.0 looks like this:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.3
Created-By: Moxie v0.9.4
Build-Jdk: 1.8.0_91
Build-Date: 2016-06-22
Implementation-Title: Gitblit
Implementation-Vendor-Id: com.gitblit
Implementation-Vendor-URL: http://gitblit.com
Implementation-Version: 1.8.0
Bundle-Name: Gitblit
Bundle-SymbolicName: gitblit
Bundle-Version: 1.8.0
Maven-Url: http://gitblit.github.io/gitblit-maven
Main-Class: org.moxie.MxLauncher
mxMain-Class: com.gitblit.GitBlitServer
mxMain-Paths: ext
```

and the manifest from 1.9.0 looks like this:

```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.2
Created-By: Moxie v0.9.4
Build-Jdk: 1.7.0_252
Build-Date: 2020-02-01
Implementation-Title: Gitblit
Implementation-Vendor-Id: com.gitblit
Implementation-Vendor-URL: http://gitblit.com
Implementation-Version: 1.9.0
Bundle-Name: Gitblit
Bundle-SymbolicName: gitblit
Bundle-Version: 1.9.0
Maven-Url: http://gitblit.github.io/gitblit-maven
Main-Class: com.gitblit.GitBlitServer
```

The most notable changes are:

- Main class changed from `org.moxie.MxLauncher` to `com.gitblit.GitblitServer`
- `mxMain-Class: com.gitblit.GitBlitServer` and `mxMain-Paths: ext` was removed

When using 1.8.0, it was possible to start gitblit using a command line like this:
```
java -jar gitblit.jar --baseFolder data
```
This was possible because the Moxie launcher automatically added the jars in the `ext` directory to the classpath. Now that this was removed, we end up with `NoClassDefFoundErrors`.

To resolve this, we have to specify the classpath explicitly **and** replace `-jar gitblit.jar` with the main class:

```
java -cp "gitblit.jar:ext/*" com.gitblit.GitBlitServer --baseFolder data
```

Note: you **have to add the quotes around the classpath**, otherwise it does not work.

Is this behavior intended? If yes, then several parts of the documentation should be updated. Also, the service scripts do not work, because they use the `-jar` version of the command. If the behavior is not intended, `ext` should be added to the classpath of gitblit.jar in the manifest.

**Comment by fzs** [comment]
This is intended, because the class path editing does not work anymore with Java 9 upwards.

You are right, the Linux service scripts were not changed. This is an oversight.
Actually this could be a problem when updating, coming to think of it. Maybe that would need a bigger change to make updates more stable. Also for many relevant distros the service scripts are rather outdated as they moved to systemd.

Which parts of the documentation are you referring to? It should all be changed, maybe I missed something.

As for the quotes, I found that it also works without the quotes, so either should be fine. Did you encounter a system where it didn't work without the quotes?

**Comment by davehofmann** [comment]
I found the old command line versions on this page: http://gitblit.com/setup_go.html
It seems like this an outdated copy of this page: http://gitblit.github.io/gitblit/setup_go.html. Here indeed all command lines are updated :)

Unfortunately the first page is the first hit on Google and github.io is not even listed on the first page, so most users will probably end up with the previous 1.8.0 documentation.

Also I would propose to add a short note on the [Upgrade GO](http://gitblit.github.io/gitblit/upgrade_go.html) page for updating to 1.9.0+ like:

---

The command line to start Gitblit changed from
```
java -jar gitblit.jar --baseFolder data
```
to
```
java -cp "gitblit.jar:ext/*" com.gitblit.GitBlitServer --baseFolder data
```
If you have installed Gitblit as a service, your service scripts need to be adjusted accordingly.

---

Speaking of service scripts: could you use one for FreeBSD? I would be happy to contribute the one I wrote.

**Comment by fzs** [comment]
If you have a service script for FreeBSD, please feel free to contribute, by all means. I do not run a FreeBSD system, or any BSD system, for that matter, so I do not test there.

Thanks for the suggestion of adding to the update page. I'll look into that when fixing the service scripts.

We are in the unfortunate situation that there is no proper redirect, or DNS entry, for gitblit.com. There is just s simple reload on the main page. Only James can change that, I cannot do anything about it.
