### ISSUE TITLE
Build fails, dependencies unavailable

### ISSUE THREAD

**Issue by mobyplum** [gitblit/gitblit#1334]
Clone repo, run ant. Build fails with<br>
    prepare:                                                                                                              
      [mx:init] =========================================================                                                 
      [mx:init] Gitblit  (1.9.1-SNAPSHOT)                                                                                 
      [mx:init] ---------------------------------------------------------                                                 
      [mx:init] project metadata                                                                                          
      [mx:init]            name: Gitblit                                                                                  
      [mx:init]     description: pure Java Git solution                                                                   
      [mx:init]         groupId: com.gitblit                                                                              
      [mx:init]      artifactId: gitblit                                                                                  
      [mx:init]         version: 1.9.1-SNAPSHOT                                                                           
      [mx:init]             url: http://gitblit.com                                                                       
      [mx:init] SHA1 checksum mismatch for http://repo.eclipse.org/content/groups/snapshots/com/google/inject/extensions/guice-servlet/4.0-gb2/guice-servlet-4.0-gb2.pom                                                                        
      [mx:init] calculated: 026bf8cdd5076014b6fc822878e0086eb44da556                                                      
      [mx:init] retrieved: <html>                                                                                         
      [mx:init] <head><title>308 Permanent Redir                                                                          
      [mx:init] Checksum file may have been cached for performance by the repository server or by a proxy server.         
      [mx:init] specify "-Dmx.enforceChecksums=false" to disable checksum verification.                                   

It looks like `http://repo.eclipse.org/content/groups/snapshots/com/google/inject/extensions/guice-servlet/4.0-gb2/guice-servlet-4.0-gb2.pom` no longer exists.

Same happens with 1.9.0 branch. Any way I can work around this?

**Comment by fzs** [comment]
Thank you for the report.

This is because the Eclipse repository switched to HTTPS only, redirecting HTTP to HTTPS, which is not handled gracefully.

This can be fixed by changing the `registeredRepositories` entries in the `build.moxie` file for the eclipse repos from `http://` to `https://`.

**Comment by mobyplum** [comment]
Thank you for the quick response!
