### ISSUE TITLE
[mx:init] Error retrieving SHA1 for com.google.inject.extensions:guice-servlet:4.0-gb2::jar   [mx:init] java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by nq963** [gitblit/gitblit#1340]
BUILD FAILED
D:\work_stp\gitblit-1.9.1\build.xml:48: org.moxie.MoxieException: java.lang.RuntimeException: Error!

Failed to download [com.google.inject.extensions:guice-servlet:4.0-gb2::jar]
Do you need to run offline?
  append "-Dmx.online=false" to your Ant launch arguments
Do you need to specify a proxy in C:\Users\zhujw\.moxie\settings.moxie?
  see http://gitblit.github.io/moxie/settings.html

**Comment by fzs** [comment]
Have you tried running it again? Maybe it was a spurious connection reset.
I cannot see which repository you are trying to connect to.

I tried a fresh build just now, with the ~/.moxie directory deleted, and it went through without problems.

**Comment by nq963** [comment]
thank you!

**Comment by nq963** [comment]
程序包HelloworldKeys不存在

**Comment by fzs** [comment]
I'm not sure what the status is now. Did it work for you? Can this be closed? Or is the problem still there?

**Comment by fzs** [comment]
HelloWorldKeys is a class, that is automatically generated when you build with running tests. Run "ant test" and it should be generated.
