### ISSUE TITLE
Russian translate

### ISSUE THREAD

**Issue by vhot2076** [gitblit/gitblit#1341]
Hi Dear, I made a Russian translate for this.  I pushed it to my fork, but I don't gamble to push it here. My translation isn`t still ideal, but it is worked. [https://github.com/vhot2076/gitblit/commit...](https://github.com/vhot2076/gitblit/commit/2dd522c7345dd366afc8ab495694757508b73870)

**Comment by fzs** [comment]
If you feel your translation is worth adding to Gitblit, please feel free to open a pull request.

**Comment by vhot2076** [comment]
Ok, did this.
