### ISSUE TITLE
GitblitAuthority NullPointerException when authority.conf has user entries that are not in users.conf

### ISSUE THREAD

**Issue by chenweichao199111** [gitblit/gitblit#1359]
authority.cmd program run occur exception, How to solve this problem？
![bug](https://user-images.githubusercontent.com/21982980/99947159-8264ba00-2db2-11eb-979f-ba5d074eff73.png)

**Comment by 1027818327** [comment]
> authority.cmd program run occur exception, How to solve this problem？
> ![bug](https://user-images.githubusercontent.com/21982980/99947159-8264ba00-2db2-11eb-979f-ba5d074eff73.png)

**Comment by flaix** [comment]
Do you have a user in your `D:\Software\gitblit-1.9.1\certs\authority.conf` file which does not exist in your user database? Check the file with a text editor, and delete entries for users that do not exits anymore.

**Comment by 1027818327** [comment]
According to the way you said, after deleting the non-existent account, the program works normally
Thank you very much


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitblit/gitblit"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月24日(星期二) 凌晨3:03
收件人:&nbsp;"gitblit/gitblit"<gitblit@noreply.github.com&gt;;
抄送:&nbsp;"晴天霹雳"<1027818327@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [gitblit/gitblit] authority.cmd program run occur exception (#1359)



 Do you have a user in your D:\Software\gitblit-1.9.1\certs\authority.conf file which does not exist in your user database? Check the file with a text editor, and delete entries for users that do not exits anymore.
