### ISSUE TITLE
Problems when using Gitblit GO as only a viewer

### ISSUE THREAD

**Issue by tttuuu888** [gitblit/gitblit#1361]
First of all, thanks a lot for development of this great program.

I'm using Gitblit GO as only a git project viewer while actually managing git projects using gitolite.  
I found 2 problems in this use case.
This may not really be a problem. In that case, please consider this as suggestion for improvement.

1. repository url is in form of "ssh://USER@192.168.0.1:2000/TEST.git"
 -> It would be nice to have an option to change to this like "git@192.168.0.1:TEST.git"

2. git repository list does not update automatically
 -> When I add new repository, Gitblit GO doesn't catch it automatically. I need to restart Gitblit Go every time I add new repository.

Thank you again.

**Comment by flaix** [comment]
The first one is already a feature requested in #904. Please feel free to vote for that issue.

The second one is loosely related to #597, which also has to do with refreshing the main page.

**Comment by tttuuu888** [comment]
@flaix Thank you for the information. 
Yes #904 is the same feature request except it didn't mention port number part. In my use case, port number also need to be removed.
#597 seems also similar to my case. 
However I will keep this issue opened if it is okay, since those are slightly different to my issues.(First might be totally same though)
Thank you again.

**Comment by tttuuu888** [comment]
I found a way to make these possible.
You can add below to your `gitblit.properties`.

1. 

```
web.otherUrls         = git@192.168.0.1:{0}
web.showSshDaemonUrls = false
```

In this way, you can add an url of `git@~` and hide default url of `ssh://~`.


2.
```
git.cacheRepositoryList = false
```

If you add this to your `gitblit.properties`, gitblit will check the repositories folder every time.


I hope this is helpful for people who are having the same problem. Thanks.
