### ISSUE TITLE
error: Missing service ImageFile

### ISSUE THREAD

**Issue by jacksongjian** [gitblit/gitblit#1371]
I use gitblit 1.9.1 on windows10. Only modified port number in defaults.properties and works well by using gitblit.cmd (web, git pull/push functions).

However it cannot work when i launch gitblitw.exe or start gitblit service in windows Service. Error info is "missing service ImageFile". 

[error] Missing service ImageFile
[error] ServiceStart returned 1

I googled it but find nothing. Please help me how to fix it, thanks.

**Comment by flaix** [comment]
There was recently a pull request,  #1370. Can the changes in there help you?

**Comment by jacksongjian** [comment]
> There was recently a pull request, #1370. Can the changes in there help you?

I already set the ARCH and CD, but still not work with the same error "[error] Missing service ImageFile" and "[error] ServiceStart returned 1"


@REM arch = x86, amd64, or ia32
SET ARCH=amd64
SET CD=D:\Software\gitblit-1.9.1\

@REM Be careful not to introduce trailing whitespace after the ^ characters.

**Comment by jacksongjian** [comment]
Is it caused by OpenJDK?
I can only use OpenJDK but not oracel JDK

**Comment by jacksongjian** [comment]
> SET CD=D:\Software\gitblit-1.9.1\



> > There was recently a pull request, #1370. Can the changes in there help you?
> 
> I already set the ARCH and CD, but still not work with the same error "[error] Missing service ImageFile" and "[error] ServiceStart returned 1"
> 
> @Rem arch = x86, amd64, or ia32
> SET ARCH=amd64
> SET CD=D:\Software\gitblit-1.9.1\
> 
> @Rem Be careful not to introduce trailing whitespace after the ^ characters.

solved this issus:

- should "SET CD=D:\Software\gitblit-1.9.1" instead of "SET CD=D:\Software\gitblit-1.9.1\"   (no last '\')

and there is a new issue "[error] Failed creating java" for me. I solved this new issue by setting the jvm.dll file in "Java" tag in gitblitw.exe. Do not use default jvm but set the specific jvm.dll with whole jvm.dll path
