### ISSUE TITLE
SSH : no matching host key type found. Their offer: ssh-rsa,ssh-dss

### ISSUE THREAD

**Issue by cshsoft** [gitblit/gitblit#1384]
Use ssh-keygen -t RSA to generate a key pair and add the public key to the account. No matching host key type found. Their offer: ssh-rsa, ssh-dSS

**Comment by andrm** [comment]
try this in .ssh/config:
Host mygitblit.server.com
 PubKeyAcceptedKeyTypes +ssh-rsa

**Comment by Huihh** [comment]
You can adding the lines below into the Host xxx.xxx.xxx.xxx(server ip)  section of your SSH configuration:

Windows systems, this file is located at %USERPROFILE%\.ssh\config or $(git_install folder)\etc\ssh\ssh_config.

Host xxx.xxx.xxx.xxx (gitblit server ip)
    HostkeyAlgorithms +ssh-rsa
    PubkeyAcceptedAlgorithms +ssh-rsa

good luck

**Comment by shreeramjoshi2000** [comment]
I used @flaix suggestion "ssh -oHostKeyAlgorithms=+ssh-rsa user@192.168.8.109." and it worked fine. But found that I had to always had to specify the HostKeyAlgorithms when ssh to the host.  Will trying @andrm method and will update this comment

**Comment by flaix** [comment]
While the original seems like a error on the client side, this was still an issue for people using OpenSSH 8.8. This has been fixed by supporting additional host key types in PR #1429

**Comment by jcasale** [comment]
@flaix Will this show up in the nightly? I looked at [docker hub](https://hub.docker.com/layers/gitblit/gitblit/nightly/images/sha256-0081b5fcc7e72a88765899469d96ea233a25f24f868ee590a52f5eedb0d5841d?context=explore) and it seems the nightly has not been updated for 7 months?

**Comment by flaix** [comment]
Yes, it should. The last nightly run failed to deploy to Docker Hub. I hope this one works, otherwise I have to make it work again.

**Comment by flaix** [comment]
@jcasale The last nightly successfully deployed to Docker Hub.
