### ISSUE TITLE
The embedded Jetty servlet container has security issue

### ISSUE THREAD

**Issue by maorui2k** [gitblit/gitblit#1390]
Here are details. Is there a new Gitblit package available?
http://www.microsoft.com/zh-cn/download/details.aspx?FamilyID=73bb1c1e-29ad-47ba-818b-80e1a0ae2c20
https://bugs.eclipse.org/bugs/show_bug.cgi?id=535669

**Comment by flaix** [comment]
We can update the Jetty to 9.2.26.v20180806 and see if nothing else breaks by this update.

**Comment by flaix** [comment]
Seems there is also a version 9.2.30.v20200428
