### ISSUE TITLE
Can't push on GitBlit after enabled verify Committer

### ISSUE THREAD

**Issue by farzadrabiee** [gitblit/gitblit#1395]
Hi,

Just integrated the LDAP with GitBlit and it synced the users too. Then disabled Local Users and enabled the `verify committer` for the repository.

After that, I set up the new Username and Email globally and committed my code. The Author and Committer are the same, But it doesn't let me push it on the GitBlit server.

It shows me this error message:
` ! [remote rejected] ... (Sorry, the account ... does not have an email address set for committer verification!)
error: failed to push some refs to 'https://myrepository.git'`

Do you have any idea how can I fix it?

Thanks

**Comment by flaix** [comment]
Have you set the correct value for the `realm.ldap.email` property to map the email attribute from LDAP?
Have you checked in Gitblit in the users page if the email addresses for the user(s) are set?

**Comment by farzadrabiee** [comment]
Thank you so much @flaix 

I just set up the value for `realm.ldap.email` and it works.
