### ISSUE TITLE
Add Certificate Chain

### ISSUE THREAD

**Issue by farzadrabiee** [gitblit/gitblit#1399]
The default Certificate Hierarchy on the `serverKeyStore.jks` file is like below:

Gitblit Certificate Authority
 |_ _ localhost

I have a trusted p12 certificate file that contains the private and public keys in it. 
I'd to add it as the Certificate Chain on Gitblit Certificate Authority.

I am wondering how can I do it?

**Comment by flaix** [comment]
Wait, aren't running Gitblit on Azure App Service? I thought Azure terminates TLS at the entry level and it never reaches your App.

Anyway, your can import your certificates into the key store, e.g with the `keytool` ([doc](https://docs.oracle.com/javase/7/docs/technotes/tools/windows/keytool.html)) command on the command line, or on your PC with a GUI like [KeystoreExplorer](https://keystore-explorer.org/). Give the certificate an identifying alias and in the Gitblit configuration set the `server.certificateAlias` setting to that same alias name.

**Comment by flaix** [comment]
Close as Done
