### ISSUE TITLE
Not Found

### ISSUE THREAD

**Issue by DebugRiders** [gitblit/gitblit#1412]
My Gitblit service is built on Windows，The project code in the ubuntu，pull or fecth is ok，push error；
Error info ： fatal: respository 'xxx/xxx/xxx.git' not found
use http

**Comment by flaix** [comment]
This is really not a lot of info to go by. I don't know what to do here.

**Comment by DebugRiders** [comment]
emmm...  I found out why，because the path to take Chinese，this is not a problem！

**Comment by DebugRiders** [comment]
ok，I created an address with Chinese。
There is no problem using English addresses！
