### ISSUE TITLE
gitblit not support PR operation

### ISSUE THREAD

**Issue by Huihh** [gitblit/gitblit#1414]
Hi, Author, I want use PR(Pull Request) operation, but almost gitblit not support it yet, Do you have a plan to support PR in the future?

**Comment by flaix** [comment]
Gitblit offers [Tickets](http://gitblit.github.io/gitblit/tickets_overview.html), which are not identical but similar to Pull requests.

**Comment by Huihh** [comment]
thank you very much, I have to learn how to use tickets
