### ISSUE TITLE
1.9.3添加ssh不起作用添加不上去

### ISSUE THREAD

**Issue by BoyceLig** [gitblit/gitblit#1422]
"1.9.3 add ssh does not work add not up"

**Comment by flaix** [comment]
I am very much suspecting this is a duplicate of #1415? Running from a container?

**Comment by BoyceLig** [comment]
我是在windows环境下运行的，我用cmd运行时，他可以添加，但是我安装了服务之后，后台运行的服务就不能添加了

**Comment by BoyceLig** [comment]
我是在Gitblit自建的网站里添加SSH的公匙，但是点击添加没反应

**Comment by BoyceLig** [comment]
具有写入权限，浏览器为Edge。我察看了#984 ，我的ssh格式是正确的，但是我在另外一台电脑去操作时候他就可以正常添加，所以我也不太清楚什么问题。我现在的电脑重新做了系统，也无法复现这个问题了。

**Comment by flaix** [comment]
If this is no longer a problem for you, please feel free to close this issue here.

**Comment by flaix** [comment]
There was another report of it not working a while ago in #1226
