### ISSUE TITLE
> Hello, it is hard to copy the link (like CTRL+C) from field "repository url" in a repository. Then can you add a button to easily do it ? A good js lib to do it is : https://clipboardjs.com/

### ISSUE THREAD

**Issue by piradix** [gitblit/gitblit#1432]
Thanks for your solution, but I use "Apache HTTP".
I will see if I can implement this solution on Apache.
Or if I have enough time to import the solution in the sources.

        > Hello, it is hard to copy the link (like CTRL+C) from field "repository url" in a repository. Then can you add a button to easily do it ? A good js lib to do it is : https://clipboardjs.com/

Thanks for the idea of ​​clipboard.js.
I have implemented it using nginx.

```
# nginx.conf
location / {
	proxy_pass	mygitblit;
	# add clipboard.min.js to html and init class cpbtn
	sub_filter   '</body>'   '<script type="text/javascript" src="https://clipboardjs.com/dist/clipboard.min.js"></script> <script type="text/javascript"> var cpbtns = new ClipboardJS(".cpbtn"); </script>  </body>';
	# replace CTRL+C btn with new btn
	subs_filter  "<img src=.*?/clippy.png.*?Enter.*?','(.*?)'.*?title=.*?>"    '<button class="cpbtn" data-clipboard-text="$1"><img src="../clippy.png"></button>' r;
}
```

This works for my gitblit GO 1.9.3 and nginx 1.18 configured with [ngx_http_substitutions_filter_module](https://github.com/yaoweibin/ngx_http_substitutions_filter_module).
I don't think it's difficult to add it to the web app via java.

_Originally posted by @tammst in https://github.com/gitblit/gitblit/issues/1431#issuecomment-1296295364_

**Comment by flaix** [comment]
I take it this was actually meant as a new comment, not a new issue.
