### ISSUE TITLE
In the repository url, the text "+RW" is overflowing (the solution )

### ISSUE THREAD

**Issue by piradix** [gitblit/gitblit#1437]
The text "+RW" is overflowing (to right) in field "URL" of a project (see image)
![Screenshot 2022-11-19 at 23-32-57 depot-test git - Gitblit](https://user-images.githubusercontent.com/64977993/202874193-96acf161-3c10-44e0-bb6c-507288466a9f.png)

To avoid it  : 
- edit file "src/main/java/com/gitblit/wicket/panels/RepositoryUrlPanel.html"
- line 16 `<img style="vertical-align: middle;padding: 0px 0px 1px 3px;" wicket:id="accessRestrictionIcon"></img>` in the style attributte add `max-width:inherit; `, you get 
```
<img style="max-width:inherit; vertical-align: middle;padding: 0px 0px 1px 3px;" wicket:id="accessRestrictionIcon"></img>
```
- save , recompile and you get  (see image 2)
![no oaverflow](https://user-images.githubusercontent.com/64977993/202874312-08fdaa10-84a5-4ea6-9495-c73b193f1411.png)

**Comment by flaix** [comment]
Can you explain to me why this makes a difference? I don't understand how that attribute on the image on the left influences the right border. Also, it seems to help but not really solve the problem completely.

<img width="577" alt="Screenshot 2022-11-20 at 17 18 15" src="https://user-images.githubusercontent.com/2362065/202913319-859c0a6d-bf85-4c37-8fd9-1a51842204a3.png">

**Comment by piradix** [comment]
before you have (look red square)
<img width="577" alt="202913319-859c0a6d-bf85-4c37-8fd9-1a51842204a3" src="https://user-images.githubusercontent.com/64977993/202917086-66771a48-d578-450d-86c4-0a748dcaf857.png">

after (if css "max-width:inherit;" is apply  on shield image ) (look red square):
![202874312-08fdaa10-84a5-4ea6-9495-c73b193f1411](https://user-images.githubusercontent.com/64977993/202917124-bdfbeeb9-4c2f-457a-9db9-e12cf16d942e.png)

I have this problem on Firefox. It's because bootstrap sets the maximum width to "100%" (of the parent) and not to the size of the image!

**Comment by flaix** [comment]
😆 I really don't know how this works.

The thing is that in the picture I attached the image on the left already has that CSS attribute set. But still the text is not fully in. But I guess I understood enough from you, to guess this is because there is a second image in that line, which also needs to have the attribute set.

**Comment by piradix** [comment]
>The thing is that in the picture I attached the image on the left already has that CSS attribute set. But still the text is not fully in. But I guess I understood enough from you, to guess this is because there is a second image in that line, which also needs to have the attribute set.

yes. there an second image : 
```
<img style="max-width:inherit; vertical-align: middle;padding: 0px 0px 1px 3px;" src="../lock_go_16x16.png" title="push authentifié">
```
