### ISSUE TITLE
Ticgit write integration?

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#305]
Originally reported on Google Code with ID 9

```
Might be useful to have ticgit write capabilities.
```

Reported by `James.Moger` on 2011-06-30 12:02:05

**Comment by fzs** [comment]
@gitblit, so, where does this stand? Can this be closed as Gitblit has tickets or should ticgit still be fully supported at some time? For example to be able to move repos between Gitblit and other products supporting ticgit?

**Comment by gitblit** [comment]
Ticgit inspired the branch ticket service. Ticgit itself is a dead end.
