### ISSUE TITLE
NullPointerException during deployment to a Weblogic container

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#495]
Originally reported on Google Code with ID 199

```
What steps will reproduce the problem?
1.deploy gitblit.war to a weblogic server container
2.start the JVM
3.not the exception

What is the expected output? What do you see instead?
expected the ap to deploy, but the deployment failed.


What version of the product are you using? On what operating system?
1.2.1, HPUX, Java-6, Weblogic 10.3.4

Please provide any additional information below.

It appears that Giblit.java is trying to call 

SevletContext.getRealPath("/") - which returns a NULL when deployed as a war file -
as stated in the API for getRealPath():

"This method returns null
if the servlet container cannot translate the virtual path
to a real path for any reason (such as when the content is
being made available from a <code>.war</code> archive).
"

See also http://stackoverflow.com/questions/536228/why-does-getrealpath-return-null-when-deployed-with-a-war-file

This was not happening in v.1.1.0.

Stack trace:

<[ACTIVE] ExecuteThread: '0' f
or queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <> <1360160594805>
<BEA-101162> <User defined liste
ner com.gitblit.GitBlit failed: java.lang.NullPointerException.
java.lang.NullPointerException
        at java.io.File.<init>(File.java:231)
        at com.gitblit.GitBlit.contextInitialized(GitBlit.java:3205)
        at com.gitblit.GitBlit.contextInitialized(GitBlit.java:3196)
        at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:481)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
....

```

Reported by `jaymeyer` on 2013-02-06 16:02:03

**Comment by jayasharma8** [comment]
Hi guys,

I am getting following error when launching and trying to login to application. Login is not wokring we noticed this issue after weblogic upgrade from 10.3.5 to 10.3.6
Env details:
Liferay 4.2
weblogic 10.3.6
jdk 1.6.181

Kindly help. we are not getting any clue and stuck.

com.liferay.portal.NoSuchLayoutSetException: No LayoutSet exists with the key {companyId=liferay.com, virtualHost=test-www.xyz.com}    at com.liferay.portal.service.persistence.LayoutSetFinder.findByC_V(LayoutSetFinder.java:86)    at com.liferay.portal.service.impl.LayoutSetLocalServiceImpl.getLayoutSet(LayoutSetLocalServiceImpl.java:105)    at sun.reflect.GeneratedMethodAccessor531.invoke(Unknown Source)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)    at java.lang.reflect.Method.invoke(Method.java:597)    at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:280)    at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:187)    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:154)    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:107)    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:176)    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:210)    at com.sun.proxy.$Proxy67.getLayoutSet(Unknown Source)    at com.liferay.portal.service.ejb.LayoutSetLocalServiceEJBImpl.getLayoutSet(LayoutSetLocalServiceEJBImpl.java:65)    at com.liferay.portal.service.ejb.LayoutSetLocalServiceEJBImpl_cwukue_ELOImpl.__WL_invoke(Unknown Source)    at weblogic.ejb.container.internal.SessionLocalMethodInvoker.invoke(SessionLocalMethodInvoker.java:39)    at com.liferay.portal.service.ejb.LayoutSetLocalServiceEJBImpl_cwukue_ELOImpl.getLayoutSet(Unknown Source)    at sun.reflect.GeneratedMethodAccessor531.invoke(Unknown Source)    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)    at java.lang.reflect.Method.invoke(Method.java:597)    at org.springframework.ejb.access.LocalSlsbInvokerInterceptor.invoke(LocalSlsbInvokerInterceptor.java:65)    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:176)    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:210)    at com.sun.proxy.$Proxy67.getLayoutSet(Unknown Source)    at com.liferay.portal.service.LayoutSetLocalServiceUtil.getLayoutSet(LayoutSetLocalServiceUtil.java:63)    at com.liferay.portal.events.ServicePreAction.getDefaultLayout(ServicePreAction.java:689)    at com.liferay.portal.events.ServicePreAction.run(ServicePreAction.java:288)    at com.liferay.portal.events.EventsProcessor._process(EventsProcessor.java:132)    at com.liferay.portal.events.EventsProcessor.process(EventsProcessor.java:70)    at com.liferay.portal.servlet.MainServlet.service(MainServlet.java:857)    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)    at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)    at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)    at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)    at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:26)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.corelogic.bis.ite.sec.websecurity.filter.XSSValidationFilter.doFilter(XSSValidationFilter.java:148)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.corelogic.bis.ite.sec.websecurity.filter.XSSValidationFilter.doFilter(XSSValidationFilter.java:148)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.liferay.filters.strip.StripFilter.doFilter(StripFilter.java:94)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.liferay.filters.secure.SecureFilter.doFilter(SecureFilter.java:143)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.liferay.filters.compression.CompressionFilter.doFilter(CompressionFilter.java:124)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.liferay.portal.servlet.filters.autologin.AutoLoginFilter.doFilter(AutoLoginFilter.java:117)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.liferay.filters.sso.cas.CASFilter.doFilter(CASFilter.java:96)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at com.liferay.portal.servlet.filters.virtualhost.VirtualHostFilter.doFilter(VirtualHostFilter.java:152)    at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:60)    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3748)    at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3714)    at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)    at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)    at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2283)    at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2182)    at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1499)    at weblogic.work.ExecuteThread.execute(ExecuteThread.java:263)    at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)<May 9, 2018 1:58:41 AM CDT> <Error> <Kernel> <BEA-000802> <ExecuteRequest failed java.lang.NullPointerException.java.lang.NullPointerException    at java.util.Hashtable.<init>(Hashtable.java:195)    at weblogic.servlet.internal.session.SessionData.convertToHashtable(SessionData.java:1411)    at weblogic.servlet.internal.session.SessionData.writeExternal(SessionData.java:1170)    at java.io.ObjectOutputStream.writeExternalData(ObjectOutputStream.java:1442)    at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1411)    Truncated. see log file for complete stacktrace>
--
