### ISSUE TITLE
Enhancement: Overriding ssh port display in ssh/web interface

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#863]
Originally reported on Google Code with ID 567

```
What steps will reproduce the problem?
1. Have a normal gitblit install
2. Proxy ssh trough haproxy, listening on port 22
3. Have no way to remove the :29814 port display in the ssh/web output

What is the expected output? What do you see instead?
There should be a way to configure gitblit to remove the port number from the git url
outputs.

What version of the product are you using? On what operating system?
1.6.2

thanks,

bernd

```

Reported by `bernd.zeimetz` on 2015-02-26 08:32:59

**Comment by fzs** [comment]
It sounds like this was actually implemented in pull request #268.
@bzed, does the new `git.sshAdvertisedPort` in v1.7.0 solve this for you?

**Comment by fzs** [comment]
@bzed, can this issue be closed?
Does the new `git.sshAdvertisedPort` meet your needs?

**Comment by fzs** [comment]
I am closing this assuming that this is implemented with the pull request mentioned above.
If that is not the case, please reopen.
