### ISSUE TITLE
Wiki style links are double-encoded

### ISSUE THREAD

**Issue by gitblit** [gitblit/gitblit#864]
Originally reported on Google Code with ID 568

```
The wiki style page links for multi-byte character page name were double-encoded, so
the link does not work.

The current environment is as follows:

- Gitblit 1.6.2
- Windows Server 2008
- Japanese character page name

If I wrote the document with this kind of link:

    [[運営]]

This should be the link as:

    http://host/doc/foo.git/master/%E9%81%8B%E5%96%B6

But the link on the Gitblit page was:

    http://host/doc/foo.git/master/%25E9%2581%258B%25E5%2596%25B6

I think the encoding method of the MarkupProcessor is not needed.

```

Reported by `yoshimov` on 2015-03-03 08:19:09

**Comment by flaix** [comment]
The surprising thing is that wiki style links a broken entirely.
For a markdown file they are not parsed to links at all, even though Pegdown should support this.
For a MediaWiki file, they are converted to links, but without a file extension the linked to file is not recognised as a wiki file. So this renders the whole MediaWiki support kind of useless. Text formatting might be usable, but any linking is rather useless. Wiki style links would have to include a file extension, which looks weird. Also, all the media wiki files need to live in the `wiki` subfolder, which is documented nowhere and rather surprising.

And yes, multi-byte characters in the link is also broken, but actually for all types, normal Markdown links too.
