### ISSUE TITLE
if zoomed in gitblit completely hides the "repository url" and git menus

### ISSUE THREAD

**Issue by skierpage** [gitblit/gitblit#910]
I couldn't see a link to clone Wikimedia Foundation's MediaWiki code.
It turns out if you're zoomed in in Firefox, gitblit's Summary window simply hides "repository url" and the [Git v] dropdown underneath it. They don't seem to be moved to an overflow menu or hamburger icon, they vanish from the UI. You can reproduce with https://dev.gitblit.com/summary/gitblit.git , just zoom in a few times until:
![gitblit summary hides repo](https://cloud.githubusercontent.com/assets/1303668/9538329/0aabd21e-4cf8-11e5-9cfe-61575ef309e1.png)

This happens in Firefox and chromium-browser.

Workaround: zoom out, but you don't know what you're missing. "Guess I'll skip this project and join another that will let me clone it."

**Comment by gitblit** [comment]
Interesting.  That is a side-effect of using a Bootstrap responsive class.

-J

**Comment by gitblit** [comment]
@skierpage This is a conflict between Bootstrap responsiveness and browser accessibility functions.  I don't know of a great way to resolve this.

I could disable the responsive behavior here to resolve your issue on a desktop browser but that will cause misleading rendering on tablets and phones.  So effectively this would only shift the problem, not solve it.

The good news for you (or maybe not so good news) is that WMF has made it clear over the last 12 months that their Gitblit install is deprecated in favor of an integrated Phabricator stack.  Perhaps your experience in that app will be better.

If you can submit a PR that resolves your issue while not shifting the problem, I'll be delighted to merge it.  For now, I'm afraid, I am closing this issue.  Sorry to disappoint.
