### ISSUE TITLE
Update Apache SSHD Library for Memory Leak

### ISSUE THREAD

**Issue by TheAjItator** [gitblit/gitblit#913]
Running GitBlit we had a memory leak problem.

We increased the heap to 2 GBs and started tuning the JVM GC to try to get by while we investigated.  Even then in a couple of weeks the memory was running low.  It was tracked to the SSHD library from Apache.  Using sshd 0.14.0 (the lastest) along with mina 2.0.9 (the latest) in our local install resulted in memory use being significantly lower and stable for weeks on end.

Therefore I'm entering this issues requesting the next releases include updates to the sshd library and dependencies to correct the memory leak.

**Comment by gitblit** [comment]
Thanks for the report.  The `develop` branch is updated to 0.14.0.
