### ISSUE TITLE
Error in documentation for the "gitbugtraq" file

### ISSUE THREAD

**Issue by mikemaaaa** [gitblit/gitblit#917]
Hello,

the example on http://gitblit.com/setup_bugtraq.html says the following:

[bugtraq "jira"]
    https://jira.atlassian.com/browse/%BUGID%
    logregex = (JRA-\\d+)

should be:

[bugtraq "jira"]
    url = https://jira.atlassian.com/browse/%BUGID%
    logregex = (JRA-\\d+)

BR

**Comment by gitblit** [comment]
Thanks.  Fixed on develop.
