### ISSUE TITLE
Use author date instead of commit date

### ISSUE THREAD

**Issue by cezariuszmarek** [gitblit/gitblit#919]
The commit list on the summary page should use author date instead of commit date to be consistent with git log output (and other tools).

**Comment by gitblit** [comment]
Interesting proposal.  Right now, you are correct, Gitblit uses the committer date.  This generally should show a linear date progression in the commit history and better-correlate with push events.  The author date is displayed within the commit/commitdiff pages.

If you are pairing Gitblit with a Gerrit-controlled/-mirrored repo, the author date is interesting but oftentimes useless and misleading for the history of the repository.

Can you cite me an example repo where using the author date in the commit list would bring clarity?

**Comment by cezariuszmarek** [comment]
It regards our private Gerrit controlled repos. Before importing repos to Gerrit I did some rebasing and rewriting to cleanup the history, so the committer date is useless for us. What's even more confusing, Git Extensions, gitk, and Git itself shows author date, so users complain, that there's something wrong with the Gitblit history view.

**Comment by gitblit** [comment]
While I would still argue that commit date makes more sense to the historical progression of a branch, I will concede that conforming to a standard expectation has merit. Switched.

**Comment by cezariuszmarek** [comment]
Thanks! Maybe it should be a configuration option?
