### ISSUE TITLE
RSS feed link ignores forward slash character

### ISSUE THREAD

**Issue by 0x084E** [gitblit/gitblit#922]
This is a minor one. The link in node rss/channel/link does not use the forward slash character if the repository is in a subdirectory.

**Comment by gitblit** [comment]
The RSS servlet doesn't need the alternate forward-slash character.  That setting exists primarily for the Wicket-based web UI or for servlets that accept multiple path parameters in a url.  The RSS servlet has a single path url component (the repo) and then optional query parameters (branch name).

Did you notice a failure or an inconsistency?

**Comment by 0x084E** [comment]
I'm not sure if we are talking about the same thing.
What I mean is not a link to a RSS feed but a link within the RSS feed. More precisely the link in rss/channel/link node (pointing to the summary page). The links within rss/channel/item/link nodes are escaped with the forward slash character but the other one uses '%2F'.

Anyways, I have IIS running as reverse proxy before gitblit GO and after your post I tried calling the url directly in gitblit which works. So this is a reverse proxy problem (or an IIS problem, I don't know if this happens with Apache, too).

**Comment by gitblit** [comment]
Yup, I see it.  The feed entries have properly formed urls, but the feed link is not.

**Comment by gitblit** [comment]
Fixed on develop.
