### ISSUE TITLE
Glitblit WAR V 1.3.2 over weblogic V 10.3.4.0 "fatal: Authentication failed" when push

### ISSUE THREAD

**Issue by senneko** [gitblit/gitblit#923]
Greetings,

That's it, I deploy de gitblit war V 1.3.2 on a weblogic V 10.3.4.0. It deploy with no problem. It works fine creating repositories and users.

When I push a local repository, it send me a "Authentication failed",  by console, there's nothing wrong.

**Comment by gitblit** [comment]
Sorry, I don't provide support for really old versions.  Have you tried 1.6.2?

**Comment by senneko** [comment]
WebLogic Server: 12.1.2.0.0
Gitblit war 1.6.2

Same problem

**Comment by senneko** [comment]
Problem solved!

For some reason, when the client try to login with the user, weblogic compare with its users first, so, to solve the problem, the same user created in Gitblit, create it in Weblogic.
