### ISSUE TITLE
incorrect chinese display in mail's subject

### ISSUE THREAD

**Issue by willyann** [gitblit/gitblit#928]
![screen shot 2015-09-30 at 14 09 04](https://cloud.githubusercontent.com/assets/5213198/10185718/a5506b1e-677d-11e5-976a-f26c043c4e21.png)

i noticed that first email envelope(????-??? #4  in attachment) subject show incorrect chinese ,
after modify "com.gitblit.service.MailService.java" 
line 199
   message.setSubject(mailing.subject);
to 
  import javax.mail.internet.MimeUtility;
  message.setSubject(MimeUtility.encodeText(mailing.subject, "utf-8", "B"));
chinese show perfect (see second envelope #5 in attachment)

this solution can be found in
http://stackoverflow.com/questions/3451256/javamail-changing-charset-of-subject-line

ps. my gitblit server (1.6.2) run on windows server 2008 R2 (english version)

**Comment by gitblit** [comment]
Great.  Would you like to open a PR with the fix?

**Comment by willyann** [comment]
yes , of course !


2015-09-30 19:22 GMT+08:00 James Moger <notifications@github.com>:
