### ISSUE TITLE
Source code viewer doesn't support '#if 0' for C/C++

### ISSUE THREAD

**Issue by sh2ka** [gitblit/gitblit#931]
This construction is used by developers to comment out the source code block if it contains multiline comments (/* */). So in this case an expected behavior is to show the code inside #if 0 ... #endif as comment because this code doesn't have sense and can mess up the user.

**Comment by gitblit** [comment]
Do you mean the syntax highlighter doesn't support `#if 0`?

**Comment by sh2ka** [comment]
Yes

**Comment by gitblit** [comment]
This will need to be addressed upstream @ [tcollard/google-code-prettify](https://github.com/tcollard/google-code-prettify).
