### ISSUE TITLE
Password with spaces got trimmed in UI

### ISSUE THREAD

**Issue by RainerW** [gitblit/gitblit#932]
Wicket has a 'bug' ( https://issues.apache.org/jira/browse/WICKET-2393 ) which does by default trim PasswordTextFields (Or any Textfield in this respect ).

For Gitblit this means that a password with spaces at the end will not work. 

Because this only affects the UI but NOT the git protocols, I would suggest fixing this 'hard, so gitblit would behave with all access protocols the same way.

**Comment by gitblit** [comment]
Hi Rainer.  I'm ok with the change, but it has to be consistent throughout the app.  I suggest creating a class like `NonTrimmedPasswordTextField` which overrides the method and using that type in the following pages:

- RootPage
- ChangePasswordPage
- EditUserPage

**Comment by RainerW** [comment]
You're right. Fixed it. Not sure how to provide the changes so you can pull ?

**Comment by gitblit** [comment]
You'd have to rebase your changes on `develop` as I am not accepting changes to `master` anymore.  Then just open a pull request.

**Comment by RainerW** [comment]
did (hopefully) a correct rebase

**Comment by RainerW** [comment]
pull request : #940

**Comment by gitblit** [comment]
Closed by #940
