### ISSUE TITLE
it's imposible to switch user after commit Merge pull request #908 from mrjoel/mrjoel-authrequestnotsession …

### ISSUE THREAD

**Issue by wangliyu** [gitblit/gitblit#936]
After the commit, it's now impossible to switch the user from one to another,

Reproduce the issue, you can first logout from one user and try login with different user, after login success, it still show the first user logged in.

**Comment by gitblit** [comment]
> After the commit, it's now impossible to switch the user from one to another,

Not in GO.  Are you running WAR?

**Comment by wangliyu** [comment]
I was able to switch user, I'm using GO.

**Comment by gitblit** [comment]
@wangliyu reported in #937 that the actual problem was not caused by pull request #908.
