### ISSUE TITLE
Allowing normal users to create repositories with LDAP authentication?

### ISSUE THREAD

**Issue by markehammons** [gitblit/gitblit#939]
I'm kind of stuck at what to do here. I would like to allow users to have a non-admin account on gitblit, but still have the ability to create personal repositories. Is there any way to support this with ldap? Trying to enable it through an admin account results in a "Failed to update user." error thanks to the LDAP.

**Comment by StephenKing** [comment]
This should work, as long as you have one (or more) groups that all users belong to and to which you can give the _can create_ privilege (for the team in Gitblit)

**Comment by markehammons** [comment]
I have a team "developers" which I tried to give create priveleges to in gitblit's ui, and I got "Failed to update team!" from it. Is there a special way to do this?

**Comment by StephenKing** [comment]
Oh, don't know. Anything interesting in the server log? I think it worked for me through the UI, otherwise you can edit the `users.conf`file

````
[team "developers"]
        role = "#create"

**Comment by markehammons** [comment]
Ah it looks like I had messed up the permissions for my system while transferring my gitblit to a new OS. Sorry about that.
