### ISSUE TITLE
Logo path does not work

### ISSUE THREAD

**Issue by spagu** [gitblit/gitblit#941]
You can add any URL or image from directory and still it is showing default one.

**Comment by jameyg42** [comment]
this "works for me"
```
web.headerLogo = ${baseFolder}/logo.png
```
where logo.png is 120x45

**Comment by fzs** [comment]
I second that. The header logo defined in `gitblit.properties` is shown.
Make sure that you have restarted the server and reloaded the page to evade caching problems.
Reopen if you can provide a way to reproduce the behaviour.
