### ISSUE TITLE
Manage system ssh and authorized_keys

### ISSUE THREAD

**Issue by adrienclerc** [gitblit/gitblit#942]
I deeply apologize if this feature request was already addressed, but I would really appreciate to see GitBlit manage SSH keys like Gogs does: it adds a line to the ~/.ssh/authorized_keys file, using its own shell to secure the connection of the SSH daemon trusted by the local administrator.
The issue with Apache SSHD is not really the trust I have (or not) in it, it's just that it must run on another port than 22 (there is already the system sshd running), and our company firewall doesn't like to route weird port outside the local area.
It's an opened discussion :)

**Comment by tomposmiko** [comment]
You can forward your 22/tcp to whatever, where gitblit iss running.
Or use capset, like:

/sbin/setcap 'cap_net_bind_service=+ep' /usr/bin/java

**Comment by adrienclerc** [comment]
Forwarding the port 22 would hide the system ssh daemon. I wouldn't be able to use and administrate the server after that change.

**Comment by tomposmiko** [comment]
I don't understand in that case, what you want.
Sorry, gogs is new to me.

But there are various options:

1. move system ssh to a different port
2. add one more IP address and use that for gitblit.
3. use ssh proxy:) like zorp....hahaha

**Comment by adrienclerc** [comment]
Gogs doesn't have an integrated ssh daemon, it relies on the one that is installed and running on the system. When a user adds its key via the web interface, it add a line to the ~/.ssh/authorized_keys with the right options so that the ssh daemon accept the connection and launch a special shell that forward everything to Gogs. Of course, the user is unique (there is only one system user for that task), but then the server recognize the user based on its credentials.
Maybe it's a totally different design that was chosen for GitBlit (especially given the Windows goal), but I think some system administrators would prefer using the SSH they know ;)

For information, here is the line Gogs add:

    command="/home/adrien/Téléchargements/gogs/gogs serv key-1 --config='/home/adrien/Téléchargements/gogs/custom/conf/app.ini'",no-port-forwarding,no-X11-forwarding,no-agent-forwarding,no-pty ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyuXa9TQ/soPmEMSQ6WCKuf+e+21a86yUoba72dh3Y7FffmKeZKYYCVhdUIaMj+JXu7MmbGfEO9HBtdvZSKP5ulaE/eB8Smq7dYAIW91iZO40CEuZLHC1gIKP0Bgksq9JHFt1EosrB6kMUyWCT10p4HhXMgEhfeQeJBp5HV2b3KjczWvurU9GRXCO+QwWOAgCvWuz8WILv5Mfi25IkiAIc6U3Kv6a8Cbcm8bfPfswbiK7qlX2k3vm1hXtC7HPGhiUkVWXLMQuwaOgnBLVI517FV1GwlcOll6XkjhxZ6oacKHHUq6a6ZuzmKYWt8r3T0CMnRikjnbT/oQT+LPjm6AL/ adrien@localhost

To fully answer your solutions:
1. If system ssh is moved to another port, then I won't be able to administrate it from a remote location. System ssh is also used by other daemon (like SVN).
2. I don't manage the IP of my company. I can't steal one for fun.
3. Breaking security is not an option either ;)

**Comment by tomposmiko** [comment]
A gave you some ideas, cannot solve your issue.
Here are some more comments:

1. If system ssh is moved to another port, then I won't be able to administrate it from a remote location. 
You system isn't flexible enough. It's always recommended to make the system flexible.
Eg. separate your services, use protocols, that can be sent through proxy easily.

3. Zorp is an application level proxy firewall, it's a security product. I suggested because AFAIK it has somewhat ssh proxy capabilities.

2. Maybe gitblit is just not for you.

When ssh feature was added @gitblit told me, that he considered system ssh, but he doesn't like its advantages over the current solution. It's unlikely, that system ssh support will be implemented ever (AFAIK).

**Comment by adrienclerc** [comment]
Thanks for your answers! I really like the idea of dealing with system ssh, but I could do without it (and managing ssh keys be hand). Every other features of Gitblit are really interesting, so I'll go with it :)

**Comment by gitblit** [comment]
Sorry I'm late to the party.

@adrienclerc Gitblit is platform independent and self-contained.  While I agree that managing the running-as user authorized keys and delegating to the system SSH server is a nice design for *nix boxes, Gitblit aims for portability across all major OSes.  There are also other advantages to having it's own SSH server like the ability to have offer SSH command plugins.

I also agree that having to specify a non-standard port is a bummer.  If someone wants to improve the docs to explain how sysadmins might proxy the SSH port, that would be a welcome improvement.  Till then I'll stick with SSH specifying a port in my SSH alias.  That works just fine for me.

**Comment by adrienclerc** [comment]
I understand that :)

If I have time (and motivation), it may be good to propose a different implementation of IPublicKeyManager that will fit this need.

**Comment by gitblit** [comment]
That's a great idea.  I'm sure there are others who'd prefer to use the native SSH service.
