### ISSUE TITLE
Add GIT Version Compatability to README.markdown

### ISSUE THREAD

**Issue by Pytry** [gitblit/gitblit#946]
I'm not able to find GIT version compatibility information anywhere.
We are currently running version 1.5.1. 
I would like to be able to upgrade to the latest stable version (1.6.2).
One of the question I need to answer before I do, is which versions of GIT are compatible with 1.6.2.
It'd be great if any was able to answer that for me.
I also thought it would be useful to add a short section in the REAME.markdown file that had a compatibility list for each stable release, as well as the current development branch.

**Comment by Pytry** [comment]
I should add, I did check the release notes for each version.

**Comment by gitblit** [comment]
Hi Keith,

I don't have such a compatibility table but it should work fine with git 1.8 or newer.  There have been improvements to the wire-protocol but they have been implemented in a way that gracefully falls-back for older git clients.

**Comment by Pytry** [comment]
Thanks. 
I will test out newer versions and see how it goes:)
