### ISSUE TITLE
Release a new gitblit release

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#952]
Hi please release a new gitblit release since there hasen't been one in a year.

**Comment by kwoot** [comment]
+1

**Comment by gitblit** [comment]
1.7.1 released.

**Comment by kwoot** [comment]
Yaiy!

**Comment by paladox** [comment]
Thanks.

**Comment by paladox** [comment]
Seems that https://dev.gitblit.com/ is not showing correctly and is very slow to load.
