### ISSUE TITLE
Improve peformance when first loading the homepage of your gitblit installation

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#954]
Currently when you go to gitblit.example.com the website takes along time to load but if you go to the repo through the link it is faster too load. Loading the homepage should be made faster.

**Comment by gitblit** [comment]
Agreed it should be faster.  I've looked into it a little.  Not sure what the problem is - but it's a VM problem.  I'll fix it sometime but it's not a high priority for me.

**Comment by paladox** [comment]
Thanks.

It is slow on Wikimedia so isen't just for dev.gitblit.org

**Comment by gitblit** [comment]
Same symptoms different problem.

**Comment by paladox** [comment]
Ok.
