### ISSUE TITLE
gitblit 1.7.1 dosen't work properly on https://dev.gitblit.com/

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#955]
Hi when loading https://dev.gitblit.com/ it is not showing correctly.

UI is not loading instead leaving just text.

**Comment by gitblit** [comment]
Yup. I'll probably dump this box when my cert expires at the end of December and move to Linode or somewhere else.

**Comment by paladox** [comment]
I get 

Line: 21
Error: '$' is undefined

error.

**Comment by paladox** [comment]
When loading the site.
