### ISSUE TITLE
Some of patches that were merged in master branch where reverted when we merged develop branch with master

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#958]
Hi changes done in master branch seem to have been reverted and some changes from develop branch were not merged. Please could these changes be re added.

**Comment by paladox** [comment]
Since master branch is the stable I would suggest going to settings in gtithub and changing default branch from master to develop so that patches are reverted by mistake because of a merge.

**Comment by gitblit** [comment]
I think I identified them and pushed them back to master.  I have also dropped the develop branch in favor of master/trunk development.  I've got too many things going on at the moment to practice git-flow.
