### ISSUE TITLE
Unable to stop gitblit 1.7.1  service under Windows 10

### ISSUE THREAD

**Issue by DrakkLord** [gitblit/gitblit#961]
Hi,

I use gitblit as a home server since I use multiple devices, so it is installed on my desktop pc which is running the latest Windows 10 ( Ver. 1511) x64 Pro.
I used v1.6.2 gitblit setup up before and it worked okay then I've seen that there is a new version out v1.7.1 I set it up ( GitBlit GO )  and it worked fine from the command line. I usually install gitblit as a service and let it do it's thing like that, this also succeeded, service installed and I was able to start it, no issues. However if I try to stop the service it hangs for a long time, I usually give up and kill the gitblit process with the task manager. I did not modify the service installer script ( installService.cmd ) so it's  on default settings. What makes this strange is that the v1.6.2 gitblit stops within a few seconds without issues with a similar setup.

Then I messed around with a few options offered by the gitblitw application it mostly made me unable to start the service or the same hanging issue when stopping the service.

**Comment by gitblit** [comment]
Hmm. Not sure what is up with that. Sounds like the shutdown code is stuck waiting for the main process to finish & join. Are you spawning processes from within gitblit through any plugins or hooks?

**Comment by DrakkLord** [comment]
I use no plugins at all and as I've seen by default the aren't any and I'm not using any hooks.

**Comment by DrakkLord** [comment]
Hello @gitblit 
I've tried this again, setting up v1.7.1 and for some reason the issue is gone, so my best guess is that either it was an issue with windows or I configured something within gitblit differently since I originally reported this issue.

**Comment by gitblit** [comment]
Great, thanks for the update.  I was struggling to explain your issue.
