### ISSUE TITLE
Gitbugtraq not working for one project

### ISSUE THREAD

**Issue by mliebelt** [gitblit/gitblit#963]
We have used on different servers (all with version 1.6.2)  in some projects the addition by defining a file `.gitbugtraq` to set a link back to our issue tracker. This worked like a charm in all cases.

However, we face currently the strange situation that only one project does not work. I have checked the following:

* Copied the same file (had to modify ID and URL) to a different repository on the same server, where it worked.
* Modified the same file directly to use the same ID and URL as above, which did not work.

So it seems to be a problem with the repository itself. How can we debug that situation further? Is there anything that can be configured additionally? Does anyone have any idea what could be wrong.

Here is the file (with some information omitted) we have used

> [bugtraq "tbes"]
>    url = https://server.id.my.company/jira/browse/%BUGID%
>    logregex = (TBES-\\\\d+)

**Comment by gitblit** [comment]
Did you put the bugtraq file on the default branch?

**Comment by mliebelt** [comment]
Sorry for the late reply, yes we did put it on the default branch. We checked that numerous times.

**Comment by gitblit** [comment]
There are no additional logging capabilities.  I think you'll have to setup a debugger to see what is wrong.

**Comment by mliebelt** [comment]
Some months later. Someone found the reason for it. Here is the short summary what fixed the issue for us.

> git clone ...
> cd ...
> git update-index --chmod=-x .gitbugtraq
> git commit -a -m "Fix permissions for gitbugtraq. (TBES-603)"
> git push

So you can close that ticket. Perhaps you could find the part of the source code where the execution flag is relevant.
