### ISSUE TITLE
Refreshing page after some time returns start page (dashboard)

### ISSUE THREAD

**Issue by 0x084E** [gitblit/gitblit#964]
Since the upgrade to version 1.7.1 i've noticed a little 'problem' when refreshing a page after some time. I have a project summary page open almost the whole day and if I leave it alone some time (i haven't measured the exact time, but 30 minutes max), come back and  refresh the page it returns the dashboard page. If I refresh a second time I get the summary page again.
I'm using Chrome and have gitblit running behind nginx, if this matters.

**Comment by gitblit** [comment]
Your session expired. It should have reauthenticated you from your cookie and it sounds like it did but perhaps being behind the proxy interfered with the page loading.

**Comment by 0x084E** [comment]
I've checked this and the behavior is the same without a proxy.

**Comment by 0x084E** [comment]
It turned out that you always get the start page for the first request after your session expired. If I open gitblit for the first time in the morning i get always the start page no matter which page was requested.

**Comment by 0x084E** [comment]
Another thing I've noticed which might be related to this. It seems that the authentication cookie expiration is not refreshed. It always expires seven days after login.

**Comment by bviktor** [comment]
Was just about to open an issue about this. It's never happened with previous releases, but with 1.7 it happens constantly. I just tested it with 30 minutes, it loads the start page, with or without a reverse proxy on top. Slightly irritating :)

**Comment by mrjoel** [comment]
I'm unable to reproduce this issue. Both waiting for the session to timeout, as well as forcing a clearing of sessions, the expected content for the page requested in the URL is returned.

What deployment mechanism are you using (war vs. GO)? Is it only a certain set of pages, or all pages? What authentication config parameters are you using? When is happens, does the URL remain the same (e.g. http://host/gitblit/summary/testA.git) and different content is presented, or the URL changes as well?

**Comment by tomposmiko** [comment]
I also have a college who noticed this.
We use gitblit with nginx proxy if it counts.

**Comment by 0x084E** [comment]
@mrjoel I'm using giblit GO on Windows and Raspbian both proxied via nginx, but it also happens if you call gitblit directly. To access it I'm using Chrome on Windows.
It seems to happen for all URLs. Open e.g. a repsotiory summary page, wait 30 minutes, press F5. The dashboard is returned while the Address is still the one for the repository summary page. Press F5 again and the correct page is returned.
Alternatively it also happens for the first time you access a non dashboard page via direct link if you have previously closed the browser. But only if you already have a valid authentication cookie.

Following my configuration (shortened)
```
git.daemonPort = 0
git.sshPort = 0
git.acceptedPushTransports = HTTP HTTPS
git.allowCreateOnPush = false
git.defaultAccessRestriction = VIEW
tickets.service = com.gitblit.tickets.FileTicketService
web.authenticateViewPages = true
web.allowGravatar = false
web.allowForking = false
web.shortCommitIdLength = 7
web.forwardSlashCharacter = !
web.summaryCommitCount = 10
web.summaryRefsCount = 10
web.summaryShowReadme = true
web.itemsPerPage = 100
web.forceDefaultLocale = en
server.httpPort = 2127
server.httpsPort = 0
server.httpBindInterface = localhost
server.httpsBindInterface = localhost
server.shutdownPort = 2129
```

Let me know if you need anything further.

**Comment by bviktor** [comment]
Here's mine:

~~~
include = defaults.properties

git.sshBindInterface = localhost
git.onlyAccessBareRepositories = true
git.acceptedPushTransports = HTTP HTTPS
git.allowCreateOnPush = false
git.packedGitLimit = 512m

tickets.service = com.gitblit.tickets.FileTicketService
tickets.closeOnPushCommitMessageRegex = (?:gfixes|gcloses)[\\s-]+#?(\\d+)

groovy.grapeFolder = ${baseFolder}/groovy-grape
groovy.postReceiveScripts = jenkins-general-postcommit
groovy.customFields = "redmineProject=Identifier of the Redmine project to which this repo is added"

web.authenticateViewPages = true
web.siteName = Foobar Git
web.canonicalUrl = https://scm.foobar.com
web.headerLogo = ${baseFolder}/foobar3.png
web.rootLink = /
web.headerBackgroundColor = #52bc7e
web.enableRpcManagement = true
web.enableRpcAdministration = true
web.allowGravatar = false
web.allowFlashCopyToClipboard = false
web.loginMessage = ${baseFolder}/md/welcome.md
web.repositoriesMessage = ${baseFolder}/md/repo.md
web.datestampLongFormat = yyyy MMMM d (EEEE)
web.datetimestampLongFormat = yyyy MMMM d (EEEE), HH:mm Z
web.showSearchTypeSelection = true
web.activityDuration = 3
web.activityDurationChoices = 1 3 7 14 21 28 60
web.activityDurationMaximum = 60
web.summaryShowReadme = true

mail.server = smtp.office365.com
mail.port = 587
mail.starttls = true
mail.username = noreply@foobar.com
mail.password = asdf
mail.fromAddress = gitblit@foobar.com
mail.adminAddresses = admin@foobar.com

realm.authenticationProviders = ldap
realm.minPasswordLength = 7
realm.ldap.server = ldap://dc2.ad.foobar.com
realm.ldap.username = ldap
realm.ldap.password = asdf
realm.ldap.maintainTeams = true
realm.ldap.accountBase = OU=Users,OU=Foobar,DC=ad,DC=foobar,DC=com
realm.ldap.groupBase = OU=LDAP,OU=Groups,OU=Foobar,DC=ad,DC=foobar,DC=com
realm.ldap.admins = "@Git Admins"
realm.ldap.email = mail
#realm.ldap.accountPattern = (&(objectClass=person)(mail=${username}))
#this is only useful for LDAP sync which we don't use
#realm.ldap.uid = sAMAccountName
realm.ldap.syncPeriod = 120 MINUTES

# This is ignored, edit /etc/sysconfig/gitblit instead !!
server.httpPort = 8080
server.httpsPort = 0
~~~

Then log in, wait half an hour, then open https://scm.foobar.com/activity or some other subpage URL directly - it will load the main page instead.

**Comment by paulsputer** [comment]
I'm running gitblit Go a3a18a0ebfeb65777ad5bd065e26fa9c00e8100c with no proxy on one of my servers.  I have been able to repeat it by waiting on the repository tree page then clicking the tickets tab for the repository. There have been occasions on certain pages (I can't recall which) that it doesn't occur.

I'll deploy the current head 56619e42f0a1e555c004374e7f2b13f744ab23f5 and see if it is resolved.  I can't recall noticing it during any eclipse debug sessions.

**Comment by paulsputer** [comment]
Right I can confirm it does still occur with the current head (56619e42f0a1e555c004374e7f2b13f744ab23f5) and can also be repeated when running from eclipse.

I seem to have narrowed it down @mrjoel to the `web.authenticateViewPages` setting.  If this is set `true` then the issue occurs, if left to the default setting `false` then correct page is loaded.

**Comment by mrjoel** [comment]
I am now using the Go version (typically use war deployment) and am easily reproducing it. I hope to have a fix soon.

**Comment by paulsputer** [comment]
@mrjoel any luck with a fix?

**Comment by valucn** [comment]
推荐中国网友使用中国头像服务，地址：https://www.cnavatar.com
