### ISSUE TITLE
clippy.swf is always loaded over http

### ISSUE THREAD

**Issue by rnd2822** [gitblit/gitblit#965]
I'm running gitblit behind a nginx webserver. Nginx does https while the request to giblit is always made via http. I'm setting the following headers for the proxy request:

```
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
```

This works for almost all resources except the clippy.swf which is always loaded over http.

Edit:
The graph in the summary page is also always loaded over http.

**Comment by QuentinC** [comment]
Exactly the same for me, but using IIS and ARR as proxy.
Everything works great but clippy.swf and graphs...

Thanks !

**Comment by fzs** [comment]
Related to #855

**Comment by flaix** [comment]
I get correct graph images by setting `X-Forwarded-Host`, `X-Forwarded-Port` and `X-Forwarded-Proto`.

The clippy issue has been solved by removing clippy and replacing it with a JS solution.
Closing this as obsolete.
