### ISSUE TITLE
Upgrade Gitblit guideline

### ISSUE THREAD

**Issue by tr4nquility** [gitblit/gitblit#971]
I can't seem to find a specific guideline on how to perform an upgrade should a newer Gitblit becomes available, thus this issue.
Currently I just simply copied everything in folder Data excluding gitblit.properties into the newer version. Is this safe..?
Otherwise, please provide a clear instruction somewhere ..

Thanks.

**Comment by gitblit** [comment]
You can copy or you can just point to the old data folder with a command-line arg or environment variable or JNDI setting.  If you are on a *nix box then you could also symlink to the old data directory.

There is some documentation about upgrading here:
[Upgrading GO](http://gitblit.com/upgrade_go.html)
[Upgrading WAR](http://gitblit.com/upgrade_war.html)

**Comment by tr4nquility** [comment]
Oh ok... My bad :(
Thanks :)

**Comment by gilbertoca** [comment]
Here is how I did(install) [it on openSUSE] (https://gist.github.com/gilbertoca/285095002a9325fbe3e3#file-gitblit_on_opensuse). Now for upgrade is just a matter of changing the WorkingDirectory variable if you are using a OS systemd compatible. And, of course, do a good  backup of the GITBLIT_BASE_FOLDER folder before start the service again with the new version.
