### ISSUE TITLE
Create a new raw nightly

### ISSUE THREAD

**Issue by paladox** [gitblit/gitblit#975]
Please create a nightly gitblit raw either a go or war probably a go file. Please.

I am not sure how to build gitblit on windows. and just want to test something quickly using latest gitblit of master branch.

**Comment by d0f** [comment]
good thanks

**Comment by gitblit** [comment]
@paladox I uploaded a snapshot build of master @ f75535759570bbc4784ee8324b0d1b8dfb01766f to [here](http://gitblit.com/gitblit-1.7.2-SNAPSHOT.zip).

**Comment by paladox** [comment]
Thanks.
