### ISSUE TITLE
Milestone due date selector with calendar view

### ISSUE THREAD

**Issue by paulsputer** [gitblit/gitblit#978]
Milestone due date would be easier to use if it displayed calendar view.  Could use inbuiult HTML5 date selector.  According to http://caniuse.com/#search=date support is already available in Edge, Chrome, Opera, Safari and Android.  For those on IE and Mozilla it would automatically remain as text. @gitblit Happy for me to do a PR for this?

**Comment by gitblit** [comment]
Yes, please.

**Comment by paulsputer** [comment]
Merged in PR #982
