### ISSUE TITLE
How to mention other users in Tickets

### ISSUE THREAD

**Issue by tr4nquility** [gitblit/gitblit#985]
This one is more of a question rather than an actual issue...
So, like the title says, how do we mention others in tickets ? 
Because there is filter "Mentioning You" in "My Tickets" menu, and I can't find out how to take advantage of this feature..

Thanks.

**Comment by gitblit** [comment]
The regex that makes this work is flawed. Having said that, "@username" is what you want.  You can check the preview to make sure it's matched.

**Comment by tr4nquility** [comment]
Oh ok.. Perhaps the regex flaw includes detecting usernames that contain "." in them?
I just tried it, and somehow rather confused. For example, the user that I want to mention is "Dhifa.Irawan".
In ticket description, if I write "@Dhifa.Irawan" then the link will become https://giturl/user/dhifa
instead of https://giturl/user/dhifa.irawan
And in "add a comment" section, if I try to mention "@Dhifa.Irawan" for the first time it won't work.
I must write it twice for the second mention to work. The first one will simply become a plain text.

**Comment by RedShift1** [comment]
I have two patches to get this started:
https://github.com/RedShift1/gitblit/commit/48bdd10bb2567a73125e710ac3c68e3b1ef9e49f
https://github.com/RedShift1/gitblit/commit/7b2160fed04db2e81dae7f9c0409c67d02708efc

The only thing that's not working is when you visit a user that has dots or other (non-whitespace) characters in them, for example https://localhost:8443/user/test.test
I'm not sure where the regex that filters that web request is at, if someone can point me in the right direction...

**Comment by rnveach** [comment]
`(?:^|\\s)@([^\\s]+)` works for me no matter where the `@` as long as it is first on the line or is preceded by a whitespace.
