### ISSUE TITLE
Documentation: character encoding in Apache reverse proxy configuration snippet

### ISSUE THREAD

**Issue by RedShift1** [gitblit/gitblit#997]
http://gitblit.com/setup_proxy.html

![gitblit charenc](https://cloud.githubusercontent.com/assets/3098010/12182214/2614df58-b587-11e5-8278-a0159b880879.png)

Should look like this:
Header edit Location ^http://([^/]+)/gitblit/ https://$1/gitblit/

**Comment by gitblit** [comment]
Good catch.  PR?

**Comment by RedShift1** [comment]
There's a repository for the website?

**Comment by gitblit** [comment]
Documentation Markdown sources are in src/site.

https://github.com/gitblit/gitblit/blob/master/src/site/setup_proxy.mkd

**Comment by RedShift1** [comment]
PR #1003
