### ISSUE TITLE
Eliminate use of Weak DH Keys

### ISSUE THREAD

**Issue by kstange** [gitblit/gitblit#998]
GitBlit GO 1.7.1, running on OpenJDK 1.8.0-65 is apparently still using weak 1024 bit keys from a common group.  Please consider updating the SSL parameters with 2048 bit keys or generate custom DH parameters for each installation.

**Comment by RedShift1** [comment]
If I recall correctly, the upper limit for Java 7 DH group is 1024 bits. If hardcoded to 2048 bits, Gitblit would no longer run on Java 7 platforms.

**Comment by gitblit** [comment]
@RedShift1 is correct.  It looks like J8 defaults to 1024 but you can set it to 2048 from the command-line. `-Djdk.tls.ephemeralDHKeySize=2048`.

**Comment by RedShift1** [comment]
We can't fix this on Java 7, but we can document it. PR #1004

**Comment by kstange** [comment]
Thanks for the solution.  Since I'm using Java 8, I've added the -D line to my startup script!
